### ISSUE TITLE
English translation for espressif-esp-iot-solution

### ISSUE THREAD

**Issue by michaelkargl** [espressif/esp-iot-solution#100]
Hello, unfortunately the documentation to the espressif-esp-iot-solution is still in chinese. I'm currently trying to find a way to properly use the Kaluga-1 LCD. Would it be possible to please translate the pages to english?

## Problem Description

Documentation linked in the README is not really in english.
```English: https://docs.espressif.com/projects/espressif-esp-iot-solution/en```

### Expected Behavior

Technical documentation is translated in english
* https://docs.espressif.com/projects/espressif-esp-iot-solution/en/latest/display/screen.html

### Steps to repropduce

1. Find reference in README file
2. Pick english from the dropdown on the bottom-left
3. Open any documentation (Screen)

**Comment by leeebo** [comment]
@michaelkargl Hi we are translating English version online docs, will be merged to github soon. And Kaluga-1 LCD code is based in https://github.com/espressif/esp-dev-kits/tree/master/esp32-s2-kaluga-1 , you can check if that help.
