### ISSUE TITLE
ssd1306水平终止范围错误

### ISSUE THREAD

**Issue by YBA0312** [espressif/esp-iot-solution#103]
[ssd1306.c 239行](https://github.com/espressif/esp-iot-solution/blob/34457c7959babfe41e88bb232ef3ae7147335243/components/display/screen/controller_driver/ssd1306/ssd1306.c#L239)
变量`x1`不需要再次-1

**Comment by DaMiBear** [comment]
是的，我也发现这个问题了，在ssd1306.c，老哥打成.h了。

**Comment by DaMiBear** [comment]
还有一个问题，也可能是我理解错了。在ssd.1306.c的271行，
`ret = LCD_WRITE(p, w * LCD_BPP / 8 * h )`
如果宽度w = 1的话，LCD_BPP = 1，那么就会导致最后的数据长度为0，所以我把 / 8 放到了最后。

**Comment by TDA-2030** [comment]
是不是和屏幕本身有关系呢？我有时候可以，有时候换个屏幕就不对了

**Comment by DaMiBear** [comment]
> 是不是和屏幕本身有关系呢？我有时候可以，有时候换个屏幕就不对了

这文件只针对于SSD1306，应该和屏幕没关系吧。我刚刚接触lvgl，个人拙见。😄

**Comment by ARC-MX** [comment]
能上传以下例程吗
