### ISSUE TITLE
Micropython

### ISSUE THREAD

**Issue by Tarun75** [espressif/esp-iot-solution#107]
## Environment

- Development Kit:      ESP32-DevKitC
- Kit version (DevKitC): [v1]
- Module or chip used:  [ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): 
    // v3.2-dev-1148-g96cd3b75c
- Build System:         MicroPython
- 
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): Micropython
   
- Operating System:     [Linux]
- Power Supply:         [USB|external 5V

## Problem Description
Need Python APIs

//Detailed problem description goes here.
Please develop IDF with supporting Python API and libraries , it is very efficient language and easy to code.

**Comment by TDA-2030** [comment]
@Tarun75 ESP32 already supports MicroPython, please see https://micropython.org/download/#esp32
