### ISSUE TITLE
Touch calibration "successful" message placement

### ISSUE THREAD

**Issue by jonshouse1** [espressif/esp-iot-solution#109]
I am using a 320x240 display in portrait.

The touch screen calibration code works well, but the placement of the "Successful" message looks odd.

I suggest modifying touch_calibration.c  with something more like this. This code should in theory place the text one text line below the screen centre with the text centre justified.

```
show_prompt_with_dir((w/2)-(Font16.Width*5), (h/2)+Font16.Height, "Successful", &Font16, COLOR_BLUE, old_dir);
```

**Comment by alic-maker** [comment]
Yes, it's not good to hard code the location of the string. I will accept your suggestion.
