### ISSUE TITLE
esp32s2/s3 usb speed

### ISSUE THREAD

**Issue by lightsalt2011** [espressif/esp-iot-solution#120]
the esp32s2/s3 drive usb 4G CAT.1 module sample code shows esp32s2/s3 only support usb 2.0 full speed mode, 
As we known  usb 2.0 full speed max speed is 12Mbps,  ONLY support usb 2.0 full speed mode(12Mbps) is the hardware limitation? 

if we use usb cdc acm(not ppp or rndis) to transfer data also be limited ?

**Comment by leeebo** [comment]
ESP32S2/S3 only supports usb1.1 full speed (same with usb2.0 full speed) depends on chip design, so any USB applications include RNDIS or CDC will have same limited speed of 12 Mbps (but for most medium-speed Cat.1 use-case, it should be enough).
