### ISSUE TITLE
can "usb_cdc_4g_module" support cat4 module? (AEGHB-418)

### ISSUE THREAD

**Issue by achao1104** [espressif/esp-iot-solution#129]
Hello,

It is good to see "usb_cdc_4g_module" support more modules, but it looks all the supported modules are 4g cat1. "usb_cdc_4g_module" can support cat4 module?

Peter

**Comment by leeebo** [comment]
Yes, Most vendor's Cat.4 modules using Compatible AT commands with CAT.1, which should work as normally as Cat.1 through the USB PPP interface. But as ESP32-S2/S3 only has USB Fullspeed (12Mbps), it's more suitable to use Cat.1.

Maybe we would add Cat.4 supported after ESP enters the USB 2.0 Highspeed (480Mbps) era.

**Comment by achao1104** [comment]
we are using sim7600jc which is cat4. shall we have to change to cat1 module, or do you have any other way? I recalled you mentioned some usb isolater.

**Comment by leeebo** [comment]
@achao1104 Yes, add a USB full-speed isolator, then attach it to the PC, find the real endpoint address of the PPP interface (Because it is a vendor specified class, the program cannot automatically identify it).

**Comment by achao1104** [comment]
thanks for your reply. what is a "USB full-speed isolator", do you have a sample link?

**Comment by leeebo** [comment]
@achao1104 Like this one:
![33ae1a864038906542ad08c6d4e4baf](https://user-images.githubusercontent.com/16922815/133233112-e9ba22fc-ff15-4463-8481-c7001ef55e80.jpg)
