### ISSUE TITLE
Add ESP32-S3-DevKitC-1 development board support

### ISSUE THREAD

**Issue by modi12jin** [espressif/esp-iot-solution#132]
![20210923010624](https://user-images.githubusercontent.com/40233017/134389391-0a963775-9935-4d4c-9001-da3d1b41b6e5.jpg)

I found that the ESP32-S3-DevKitC-1 development board is already on sale, when will it be supported?

**Comment by alic-maker** [comment]
A considerable part of the functions should be directly usable, and some unusable functions are still under development. You can try to start your work now.
