### ISSUE TITLE
Add support for ESP32-S3 I2S (feature request)

### ISSUE THREAD

**Issue by DCSBL** [espressif/esp-iot-solution#136]
## Environment

- Development Kit: none
- Kit version (for WroverKit/PicoKit/DevKitC): -
- Module or chip used:  ESP32-S3
- IDF version (run ``git describe --tags`` to find it): V4.3.1
- Build System: CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): `xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0`
- Operating System: macOS
- Power Supply: USB

## Problem Description
It would be nice if I2S support is added to the ESP32-S3, so the ESP32-S3 can start to control LCD screen over this bus. When looking at [these files](https://github.com/espressif/esp-iot-solution/tree/master/components/bus), only the ESP32 and ESP32-S2 is supported.

**Comment by leeebo** [comment]
@DCSBL ESP32-S3 LCD driver is under development, will mention you if ready

**Comment by DCSBL** [comment]
Thanks!
I recently found out that IDF V4.4 natively supports LCD over I2S. So for me it is not required anymore to have the support here.
