### ISSUE TITLE
esp32s3 使用usb_camera_lcd_display   报错  uvc_stream.c:689 (_usb_pipe_init):pipe alloc failed 

### ISSUE THREAD

**Issue by helloyifa** [espressif/esp-iot-solution#148]
在使用usb_camera_lcd_display 例子时  出现如下错误提示  
E (3899) UVC_STREAM: IDF/esp-iot-solution/components/usb/uvc_stream/uvc_stream.c:689 (_usb_pipe_init):pipe alloc failed
E (3911) UVC_STREAM: IDF/esp-iot-solution/components/usb/uvc_stream/uvc_stream.c:1320 (_usb_processing_task):stream pipe 
这个问题该如何解决

完整日志如下：
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x17f4
load:0x403b6000,len:0xb74
load:0x403ba000,len:0x3008
entry 0x403b61ec
I (24) boot: ESP-IDF v4.4-beta1-183-gf23dcd3555 2nd stage bootloader
I (25) boot: compile time 15:34:46
I (25) boot: chip revision: 0
I (28) qio_mode: Enabling default flash chip QIO
I (33) boot.esp32s3: Boot SPI Speed : 80MHz
I (38) boot.esp32s3: SPI Mode       : QIO
I (43) boot.esp32s3: SPI Flash Size : 4MB
I (48) boot: Enabling RNG early entropy source...
W (53) bootloader_random: RNG for ESP32-S3 not currently supported
I (60) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (71) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (78) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (86) boot:  2 factory          factory app      00 00 00010000 00177000
I (93) boot:  3 storage          Unknown data     01 82 00187000 001f4000
I (101) boot: End of partition table
I (105) esp_image: segment 0: paddr=00010020 vaddr=3c050020 size=10534h ( 66868) map
I (124) esp_image: segment 1: paddr=0002055c vaddr=3fc93b00 size=028dch ( 10460) load
I (126) esp_image: segment 2: paddr=00022e40 vaddr=40374000 size=0d1d8h ( 53720) load
I (140) esp_image: segment 3: paddr=00030020 vaddr=42000020 size=4636ch (287596) map
I (184) esp_image: segment 4: paddr=00076394 vaddr=403811d8 size=02920h ( 10528) load
I (187) esp_image: segment 5: paddr=00078cbc vaddr=50000000 size=00010h (    16) load
I (196) boot: Loaded app from partition at offset 0x10000
I (196) boot: Disabling RNG early entropy source...
W (202) bootloader_random: RNG for ESP32-S3 not currently supported
I (220) cpu_start: Pro cpu up.
I (220) cpu_start: Starting app cpu, entry point is 0x40375340
0x40375340: call_start_cpu1 at E:/work/esp_idf/4.4/components/esp_system/port/cpu_start.c:156

I (0) cpu_sar;3:mWAp22c)urucp.t[0malibration efuse version does not match, set default version: 0

I (239) cpu_start: Pro cpu start user code
I (240) cpu_start: cpu freq: 240000000
I (240) cpu_start: Application information:
I (242) cpu_start: Project name:     uvc_mjpeg_lcd
I (248) cpu_start: App version:      v4.4-beta1-183-gf23dcd3555
I (254) cpu_start: Compile time:     Dec 17 2021 16:28:12
I (260) cpu_start: ELF file SHA256:  39d7dc3d6e8f6c35...
I (266) cpu_start: ESP-IDF:          v4.4-beta1-183-gf23dcd3555
I (273) heap_init: Initializing. RAM available for dynamic allocation:
I (280) heap_init: At 3FC971E0 len 00048E20 (291 KiB): D/IRAM
I (287) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (293) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (300) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (306) spi_flash: detected chip: gd
I (310) spi_flash: flash io: qio
W (314) spi_flash: Detected size(8192k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
I (327) sleep: Configure to isolate all GPIO pins in sleep state
I (334) sleep: Enable automatic switching of GPIO sleep configuration
I (341) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (358) spi_bus: SPI2 bus created
I (362) spi_bus: SPI2 bus device added, CS=10 Mode=0 Speed=80000000
I (570) lcd st7789: MADCTL=60
I (570) uvc_demo: Screen name:ST7789 | width:320 | height:240
I (3502) UVC_STREAM: UVC Streaming Config Succeed
E (3503) uvc_demo: uvc streaming config success
I (3553) UVC_STREAM: UVC Streaming Starting
I (3583) UVC_STREAM: Port=1 init succeed
I (3583) UVC_STREAM: Waitting USB Connection
I (3833) UVC_STREAM: line 353 HCD_PORT_EVENT_CONNECTION
I (3833) UVC_STREAM: Resetting Port
I (3893) UVC_STREAM: Setting Port FIFO
I (3893) UVC_STREAM: Getting Port Speed
I (3893) UVC_STREAM: Port speed = 0
I (3895) UVC_STREAM: USB Speed: low-speed
E (3899) UVC_STREAM: IDF/esp-iot-solution/components/usb/uvc_stream/uvc_stream.c:689 (_usb_pipe_init):pipe alloc failed
E (3911) UVC_STREAM: IDF/esp-iot-solution/components/usb/uvc_stream/uvc_stream.c:1320 (_usb_processing_task):stream pipe create failed
W (3923) UVC_STREAM: Resetting USB Driver
W (3928) UVC_STREAM: Resetting default pipe
I (3933) UVC_STREAM: pipe state = 0
W (4137) UVC_STREAM: Pipe wait event timeout
I (4137) UVC_STREAM: hcd recovering
I (4187) UVC_STREAM: hcd port state = 6
I (4387) UVC_STREAM: Waitting USB Connection

**Comment by leeebo** [comment]
`I (3895) UVC_STREAM: USB Speed: low-speed` shows you are trying to connect to a Low-speed device that could not be a UVC Camera. 

I guess it is a hardware wiring error. Please switch the D+ D- cable and try again
