### ISSUE TITLE
usb host  . how to read hidkeyboard or hidmouse (AEGHB-75)

### ISSUE THREAD

**Issue by 3050311118** [espressif/esp-iot-solution#151]
will you provide some examples

**Comment by leeebo** [comment]
@3050311118 Sorry, we currently do not support Host HID.

**Comment by versamodule** [comment]
I am a bit confused about this because you have the example: 
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/usb_host_lib
Which does spit out the information when I plug a keyboard into my ESP32-S3.

**Comment by leeebo** [comment]
The Host HID has been supported in https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/hid, which supports USB Mouse and Keyboards with HID boot protocol.
