### ISSUE TITLE
what is the baudrate for usb_cdc_4g_module

### ISSUE THREAD

**Issue by achao1104** [espressif/esp-iot-solution#153]
Hello,

From the log, I see "CONNECT 115200", and then what is the baudrate used for usb in the sample? is there an option to set? thanks.

Peter

I (23143) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:ATD*99***1#

I (23160) esp-modem-dte: esp_dte_handle_line(80): Recv:
CONNECT 115200

I (23161) usb4gutil: Modem PPP Started
W (23162) usb4gutil: PPP netif event = 259
W (23167) usb4gutil: PPP netif event = 262
W (23176) usb4gutil: PPP netif event = 263
W (23177) usb4gutil: PPP netif event = 265
I (23198) esp-netif_lwip-ppp: Connected
I (23199) esp-netif_lwip-ppp: Name Server1: 183.230.126.225
I (23199) esp-netif_lwip-ppp: Name Server2: 183.230.126.224
I (23204) usb4gutil: IP event! 6
I (23208) usb4gutil: Modem Connected to PPP Server
I (23214) usb4gutil: ppp ip: 10.102.179.74, mask: 255.255.255.255, gw: 10.64.64.64
I (23222) usb4gutil: Main DNS: 183.230.126.225
I (23227) usb4gutil: Backup DNS: 183.230.126.224

**Comment by leeebo** [comment]
@achao1104 This baudrate param is meaningless for USB ports, which will try best to transfer more data.

**Comment by achao1104** [comment]
thanks
