### ISSUE TITLE
USB_HCDC: line 267 HCD_PORT_EVENT_DISCONNECTION for usb_cdc_4g_module (AEGHB-74)

### ISSUE THREAD

**Issue by achao1104** [espressif/esp-iot-solution#155]
Hello,

It can setup the connection successfully, and I also can upload some data to my cloud sever through usb_cdc_4g_module, but occasionally, it reports "HCD_PORT_EVENT_DISCONNECTION" and then it can not connect server.

W (30035) USB_HCDC: line 267 HCD_PORT_EVENT_DISCONNECTION
I (30039) USB_HCDC: hcd port state = 7
W (30043) USB_HCDC: Resetting USB Driver
W (30048) USB_HCDC: Waitting for CDC task delete
I (30053) USB_HCDC: pipe state = 0
I (30057) USB_HCDC: pipe state = 0
I (30261) USB_HCDC: CDC task deleted
W (30263) USB_HCDC: Resetting default pipe
I (30263) USB_HCDC: pipe state = 0
I (30271) bizutil: bat adc 85
I (30271) bizutil: power is ok 85
I (30277) bizutil: af10 data packed len 37
I (30277) main: sensor data len 37
I (30280) bizutil: sensor server_send sucess
I (30463) USB_HCDC: hcd recovering
I (30513) USB_HCDC: Waitting USB Connection
I (30513) USB_HCDC: Port power: ON

**Comment by achao1104** [comment]
hello, could anybody reply? thanks.

**Comment by leeebo** [comment]
@achao1104  Please check the power supply of the 4G module, the peak current is very high (~2A) and may shutdown unexpectedly if not reached

**Comment by achao1104** [comment]
thanks, our hardware can support peak current 3A.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-iot-solution"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 中午11:14
***@***.***&gt;;
抄送:&nbsp;"Peter ***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-iot-solution] USB_HCDC: line 267 HCD_PORT_EVENT_DISCONNECTION for usb_cdc_4g_module (Issue #155)





 
@achao1104  Please check the power supply of the 4G module, the peak current is very high (~2A) and may shutdown unexpectedly if not reached
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leeebo** [comment]
@achao1104 Could you please add your full log?

**Comment by achao1104** [comment]
Thanks, here is it.




I (21) boot: ESP-IDF v4.4-beta1-284-gd83021a6e8-dirt 2nd stage bootloader
I (21) boot: compile time 10:23:01
I (22) boot: chip revision: 0
I (26) qio_mode: Enabling default flash chip QIO
I (31) boot.esp32s2: SPI Speed&nbsp; &nbsp; &nbsp; : 80MHz
I (36) boot.esp32s2: SPI Mode&nbsp; &nbsp; &nbsp; &nbsp;: QIO
I (41) boot.esp32s2: SPI Flash Size : 4MB
I (45) boot: Enabling RNG early entropy source...
I (51) boot: Partition Table:
I (54) boot: ## Label&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Usage&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Type ST Offset&nbsp; &nbsp;Length
I (62) boot:&nbsp; 0 nvs&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; WiFi data&nbsp; &nbsp; &nbsp; &nbsp; 01 02 00009000 00005000
I (69) boot:&nbsp; 1 otadata&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; OTA data&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;01 00 0000e000 00002000
I (77) boot:&nbsp; 2 ota_0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; OTA app&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 00 10 00010000 00100000
I (84) boot:&nbsp; 3 ota_1&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; OTA app&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 00 11 00110000 00100000
I (92) boot:&nbsp; 4 storage&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Unknown data&nbsp; &nbsp; &nbsp;01 82 00210000 001e0000
I (99) boot:&nbsp; 5 coredump&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Unknown data&nbsp; &nbsp; &nbsp;01 03 003f0000 00010000
I (107) boot: End of partition table
I (111) boot: No factory image, trying OTA 0
I (116) esp_image: segment 0: paddr=00010020 vaddr=3f000020 size=25798h (153496) map
I (151) esp_image: segment 1: paddr=000357c0 vaddr=3ffca3d0 size=037bch ( 14268) load
I (154) esp_image: segment 2: paddr=00038f84 vaddr=40024000 size=07094h ( 28820) load
I (163) esp_image: segment 3: paddr=00040020 vaddr=40080020 size=928a4h (600228) map
I (268) esp_image: segment 4: paddr=000d28cc vaddr=4002b094 size=0f330h ( 62256) load
I (282) esp_image: segment 5: paddr=000e1c04 vaddr=40070000 size=0002ch (&nbsp; &nbsp; 44) load
I (282) esp_image: segment 6: paddr=000e1c38 vaddr=50000800 size=0001ch (&nbsp; &nbsp; 28) load
I (298) boot: Loaded app from partition at offset 0x10000
I (315) boot: Set actual ota_seq=1 in otadata[0]
I (315) boot: Disabling RNG early entropy source...
I (326) cache: Instruction cache&nbsp; &nbsp; &nbsp; &nbsp; : size 8KB, 4Ways, cache line size 32Byte
I (326) cache: Data cache&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: size 8KB, 4Ways, cache line size 32Byte
I (331) spiram: Found 16MBit SPI RAM device
I (336) spiram: SPI RAM mode: sram 80m
I (341) spiram: PSRAM initialized, cache is in normal (1-core) mode.
I (348) cpu_start: Pro cpu up.
I (570) sf�ff���*��SRAM memory test OK
I (579) cpu_start: Pro cpu start user code
I (579) cpu_start: cpu freq: 240000000
I (579) cpu_start: Application information:
I (582) cpu_start: Project name:&nbsp; &nbsp; &nbsp;solardevice
I (587) cpu_start: App version:&nbsp; &nbsp; &nbsp; 19
I (592) cpu_start: Compile time:&nbsp; &nbsp; &nbsp;Jan&nbsp; 7 2022 11:23:30
I (598) cpu_start: ELF file SHA256:&nbsp; 3d2698e7f92e6c49...
I (604) cpu_start: ESP-IDF:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; v4.4-beta1-284-gd83021a6e8-dirt
I (611) heap_init: Initializing. RAM available for dynamic allocation:
I (618) heap_init: At 3FF9E02C len 00001FC4 (7 KiB): RTCRAM
I (624) heap_init: At 3FFD21C8 len 00029E38 (167 KiB): D/IRAM
I (631) heap_init: At 3FFFC000 len 00003A10 (14 KiB): DRAM
I (637) spiram: Adding pool of 2048K of external SPI memory to heap allocator
I (645) spi_flash: detected chip: gd
I (649) spi_flash: flash io: qio
W (653) spi_flash: Detected size(8192k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
I (669) cpu_start: Starting scheduler on PRO CPU.
I (672) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (680) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (689) util: dog1_task started
I (693) gpio: GPIO[16]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (702) util: restart_task started
I (745) fatfile: Partition size: total: 1799921, used: 753
I (746) gpio: GPIO[14]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (750) i2cutil: i2c init
I (815) util: file /spiffs/config.bin write success 290
I (815) util: config write 290 bytes,include md5
I (816) util: config read success 274 bytes,not include md5
I (985) bizutil: bat adc 85
I (985) bizutil: power is ok 85
I (1349) util: led changed to 100|2000
I (1354) otautil: configured ota_0 type 00 subtype 10 address 10000 size 100000
I (1362) otautil: running ota_0 type 00 subtype 10 address 10000 size 100000
I (1370) otautil: next ota_1 type 00 subtype 11 address 110000 size 100000
I (1377) otautil: running firmware version: 19
I (1403) util: file /spiffs/slave.bin not exist
I (1404) bizutil: slave device not exist
W (1404) usb4gutil: usb4g_init
I (1459) USB_HCDC: usb driver install succeed
I (1459) USB_HCDC: Waitting Device Connection
I (1489) USB_HCDC: USB Port=1 init succeed
I (1489) USB_HCDC: Waitting USB Connection
I (1489) USB_HCDC: Port power: ON
I (8184) USB_HCDC: line 263 HCD_PORT_EVENT_CONNECTION
I (8184) USB_HCDC: Resetting Port
I (8244) USB_HCDC: Port reset succeed
I (8244) USB_HCDC: Getting Port Speed
I (8244) USB_HCDC: Port speed = 1
I (8245) USB_HCDC: USB Speed: full-speed
I (8250) USB_HCDC: Set Device Addr = 1
I (8254) USB_HCDC: Set Device Addr Done
I (8259) USB_HCDC: Set Device Configuration = 1
I (8264) USB_HCDC: Set Device Configuration Done
I (8269) USB_HCDC: Creating bulk in pipe
I (8274) USB_HCDC: Creating bulk out pipe
I (8279) USB_HCDC: Device Connected
W (8284) usb4gutil: modem_board_start_up called
I (8288) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (8796) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutm_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (8801) usb4gutil: cpin 0|360
I (8805) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (9314) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutm_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (9319) usb4gutil: cpin 1|360
I (9323) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (9832) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutm_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (9838) usb4gutil: cpin 2|360
I (9841) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (10350) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutem_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (10356) usb4gutil: cpin 3|360
I (10359) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (10868) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutem_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (10874) usb4gutil: cpin 4|360
I (10878) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (11386) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutem_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (11392) usb4gutil: cpin 5|360
I (11396) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (11904) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutem_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (11910) usb4gutil: cpin 6|360
I (11914) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (12422) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutem_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (12428) usb4gutil: cpin 7|360
I (12431) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (12940) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutem_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (12946) usb4gutil: cpin 8|360
I (12949) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (13458) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutem_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (13464) usb4gutil: cpin 9|360
I (13468) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


E (13976) esp-modem-dte: esp_modem_dte_send_cmd(197): process command timeout
&nbsp;response timeoutem_dce: esp_modem_dce_generic_command(31): Command:AT+CPIN?
I (13982) usb4gutil: cpin 10|360
I (13986) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


I (14407) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CME ERROR: SIM busy




W (14407) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+CPIN?
...failed
I (14413) usb4gutil: cpin 11|360
I (14917) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CPIN?


I (14920) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CPIN: READY


OK




I (14923) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (14934) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 99,99


OK




I (15440) usb4gutil: csq 0|80
I (15440) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (15444) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 99,99


OK




I (15949) usb4gutil: csq 1|80
I (15949) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (15954) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 99,99


OK




I (16458) usb4gutil: csq 2|80
I (16458) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (16463) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 99,99


OK




I (16967) usb4gutil: csq 3|80
I (16967) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (16969) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 99,99


OK




I (17476) usb4gutil: csq 4|80
I (17476) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (17478) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 99,99


OK




I (17985) usb4gutil: csq 5|80
I (17985) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (17987) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 99,99


OK




I (18494) usb4gutil: csq 6|80
I (18494) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (18497) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 99,99


OK




I (19003) usb4gutil: csq 7|80
I (19003) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (19006) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 99,99


OK




I (19512) usb4gutil: csq 8|80
I (19512) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CSQ


I (19515) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CSQ: 28,99


OK




I (20021) usb4gutil: csq 28
I (20021) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CGSN


I (20025) esp-modem-dte: esp_dte_handle_line(80): Recv:
863949040221131


OK




I (20030) usb4gutil: imei 863949040221131
I (20035) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CICCID


I (20048) esp-modem-dte: esp_dte_handle_line(80): Recv:
+ICCID: 89860487212070542549


OK




I (20053) usb4gutil: iccid 89860487212070542549
I (20059) usb4gutil: apn CMNET,user ***@***.***,password 888,auth 1
I (20065) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT


I (20075) esp-modem-dte: esp_dte_handle_line(80): Recv:
OK




I (20080) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:ATE0


I (20090) esp-modem-dte: esp_dte_handle_line(80): Recv:
OK




I (20095) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+IFC=0,0


I (20106) esp-modem-dte: esp_dte_handle_line(80): Recv:
OK




I (22111) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CGDCONT=1,"IP","CMNET"


I (22141) esp-modem-dte: esp_dte_handle_line(80): Recv:
OK




I (22142) esp_modem_dce: esp_modem_dce_generic_command(27): Sending ***@***.***"


I (22157) esp-modem-dte: esp_dte_handle_line(80): Recv:
OK




I (22157) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:AT+CEREG=2;+CEREG?


I (22167) esp-modem-dte: esp_dte_handle_line(80): Recv:
+CEREG: 2,1,18C8,CF59250,7


OK




I (22173) esp_modem_dce: esp_modem_dce_generic_command(27): Sending command:ATD*99***1#


I (22192) esp-modem-dte: esp_dte_handle_line(80): Recv:
CONNECT 115200




I (22193) usb4gutil: Modem PPP Started
W (22195) usb4gutil: PPP netif event = 259
W (22199) usb4gutil: PPP netif event = 262
W (22210) usb4gutil: PPP netif event = 263
W (22211) usb4gutil: PPP netif event = 265
I (22231) esp-netif_lwip-ppp: Connected
I (22231) esp-netif_lwip-ppp: Name Server1: 120.196.165.7
I (22231) esp-netif_lwip-ppp: Name Server2: 221.179.38.7
I (22237) usb4gutil: IP event! 6
I (22240) usb4gutil: Modem Connected to PPP Server
I (22246) usb4gutil: ppp ip: 10.92.215.45, mask: 255.255.255.255, gw: 10.64.64.64
I (22254) usb4gutil: Main DNS: 120.196.165.7
I (22259) usb4gutil: Backup DNS: 221.179.38.7
W (22264) usb4gutil: PPP netif event = 266
W (22269) usb4gutil: wifiutil_init
I (22273) usb4gutil: ap dns addr(auto): 120.196.165.7
I (22280) wifi:wifi driver task: 3ffd985c, prio:23, stack:3584, core=0
I (22285) system_api: Base MAC address is not set
I (22290) system_api: read default base MAC address from EFUSE
I (22299) wifi:wifi firmware version: 0d44bbe
I (22301) wifi:wifi certification version: v7.0
I (22305) wifi:config NVS flash: enabled
I (22309) wifi:config nano formating: disabled
I (22313) wifi:Init data frame dynamic rx buffer num: 32
I (22318) wifi:Init management frame dynamic rx buffer num: 32
I (22324) wifi:Init management short buffer num: 32
I (22328) wifi:Init static tx buffer num: 16
I (22333) wifi:Init tx cache buffer num: 32
I (22336) wifi:Init static rx buffer size: 1600
I (22340) wifi:Init static rx buffer num: 10
I (22344) wifi:Init dynamic rx buffer num: 32
I (22349) wifi_init: rx ba win: 6
I (22352) wifi_init: tcpip mbox: 32
I (22356) wifi_init: udp mbox: 6
I (22360) wifi_init: tcp mbox: 6
I (22364) wifi_init: tcp tx win: 5744
I (22369) wifi_init: tcp rx win: 5744
I (22373) wifi_init: tcp mss: 1440
I (22377) wifi_init: WiFi/LWIP prefer SPIRAM
I (22382) wifi_init: WiFi IRAM OP enabled
I (22387) wifi_init: WiFi RX IRAM OP enabled
I (22392) phy_init: phy_version 1800,e7ef680,Apr 13 2021,11:45:08
I (22488) wifi:mode : softAP (7c:df:a1:09:4a:7b)
I (22490) wifi:Total power save buffer number: 8
I (22490) wifi:Init max length of beacon: 752/752
I (22491) wifi:Init max length of beacon: 752/752
I (22499) wifi:Total power save buffer number: 8
I (22501) usb4gutil: NAT is enabled
W (22503) main: main started version 19,reset 1,seconds 21 wake 0
I (23510) bizutil: ota socket created 54, connecting to 203.145.18.63:36000
I (23677) bizutil: ota successfully connected 203.145.18.63:36000
I (23677) bizutil: af10 data packed len 38
I (24931) otautil: ota not need to upgrade
I (24931) bizutil: ota biz sock 54 closed
I (24932) bizutil: config sent len 274
I (24934) bizutil: af10 data packed len 310
I (24939) bizutil: config socket created 54, connecting to 203.145.18.63:36000
I (25097) bizutil: config successfully connected 203.145.18.63:36000
I (25098) bizutil: config server_send sucess
I (25253) bizutil: config recv3 2
I (25254) bizutil: config rsp:kk
I (25276) util: file /spiffs/sta.bin not exist
I (25277) bizutil: no system status file,skip
I (25277) bizutil: dump no
I (25322) bizutil: no slave device id list
I (25322) util: sntp update ...
I (26478) util: datetime_sync_cb:&nbsp; Fri Jan&nbsp; 7 12:30:57 2022
I (26478) util: sntp update success
I (26479) util: datetime_sync:&nbsp; Fri Jan&nbsp; 7 12:30:57 2022
W (26485) USB_HCDC: line 267 HCD_PORT_EVENT_DISCONNECTION
I (26489) USB_HCDC: hcd port state = 7
W (26494) USB_HCDC: Resetting USB Driver
W (26498) USB_HCDC: Waitting for CDC task delete
I (26503) USB_HCDC: pipe state = 0
I (26508) USB_HCDC: pipe state = 0
I (26712) USB_HCDC: CDC task deleted
W (26713) USB_HCDC: Resetting default pipe
I (26713) USB_HCDC: pipe state = 0
I (26722) bizutil: bat adc 27
I (26722) bizutil: power is ok 27
I (26728) bizutil: af10 data packed len 37
I (26728) main: sensor data len 37
I (26731) bizutil: sensor server_send sucess
I (26914) USB_HCDC: hcd recovering
I (26964) USB_HCDC: Waitting USB Connection
I (26964) USB_HCDC: Port power: ON
E (56735) bizutil: sensor server_send recv2: len -1 errno 11
I (56735) bizutil: sensor biz sock 54 closed





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-iot-solution"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 中午11:30
***@***.***&gt;;
抄送:&nbsp;"Peter ***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-iot-solution] USB_HCDC: line 267 HCD_PORT_EVENT_DISCONNECTION for usb_cdc_4g_module (Issue #155)





 
@achao1104 Could you please add your full log?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by achao1104** [comment]
It looks ok with your old branch, but has problem with v4.4 release.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-iot-solution"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 中午11:30
***@***.***&gt;;
抄送:&nbsp;"Peter ***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-iot-solution] USB_HCDC: line 267 HCD_PORT_EVENT_DISCONNECTION for usb_cdc_4g_module (Issue #155)





 
@achao1104 Could you please add your full log?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leeebo** [comment]
@achao1104 The new [iot_usbh_modem diver](https://github.com/espressif/esp-iot-solution/tree/master/components/usb/iot_usbh_modem) which support self-recover through daemon task can handle most of the issues, please try with the [example](https://github.com/espressif/esp-iot-solution/tree/master/examples/usb/host/usb_cdc_4g_module).
