### ISSUE TITLE
usb_camera_lcd_display--> usb camera config success, but no data come out from camera

### ISSUE THREAD

**Issue by W00ng** [espressif/esp-iot-solution#156]
## Environment
- Module or chip used:  ESP32-S3R2
- IDF version：v4.4-beta1-183-gf23dcd3555
- Operating System:     Window
- Power Supply:         USB

## Problem Description
1.usb_camera_lcd_display
2.usb camera config success, but no data come out from camera
3.terminal log show below 

## Debug Logs

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x17fc
load:0x403b6000,len:0xb74
load:0x403ba000,len:0x3008
entry 0x403b61ec
I (24) boot: ESP-IDF v4.4-beta1-183-gf23dcd3555-dirt 2nd stage bootloader
I (25) boot: compile time 00:13:24
I (25) boot: chip revision: 0
I (28) qio_mode: Enabling QIO for flash chip WinBond
I (34) boot.esp32s3: Boot SPI Speed : 80MHz
I (39) boot.esp32s3: SPI Mode       : QIO
I (44) boot.esp32s3: SPI Flash Size : 8MB
I (48) boot: Enabling RNG early entropy source...
W (54) bootloader_random: RNG for ESP32-S3 not currently supported     
I (61) boot: Partition Table:
I (64) boot: ## Label            Usage          Type ST Offset   Length
I (71) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (79) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (86) boot:  2 factory          factory app      00 00 00010000 002ee000
I (94) boot:  3 storage          Unknown data     01 82 002fe000 00100000
I (101) boot: End of partition table
I (106) esp_image: segment 0: paddr=00010020 vaddr=3c040020 size=0f19ch ( 61852) map
I (124) esp_image: segment 1: paddr=0001f1c4 vaddr=3fc96fc0 size=00e54h (  3668) load
I (125) esp_image: segment 2: paddr=00020020 vaddr=42000020 size=3b6b0h (243376) map
I (168) esp_image: segment 3: paddr=0005b6d8 vaddr=3fc97e14 size=01a20h (  6688) load
I (169) esp_image: segment 4: paddr=0005d100 vaddr=40378000 size=0efc0h ( 61376) load
I (185) esp_image: segment 5: paddr=0006c0c8 vaddr=50000000 size=00010h (    16) load
I (191) boot: Loaded app from partition at offset 0x10000
I (192) boot: Disabling RNG early entropy source...
W (194) bootloader_random: RNG for ESP32-S3 not currently supported
I (212) spiram: Found 16MBit SPI RAM device
I (213) spiram: SPI RAM mode: sram 80m
I (213) spiram: PSRAM initialized, cache is in normal (1-core) mode.
I (218) cpu_start: Pro cpu up.
I (221) cpu_start: Starting app cpu, entry point is 0x403792ec
0x403792ec: call_start_cpu1 at D:/esp-idf/components/esp_system/port/cpu_start.c:156

I (0) cpu_start: App cpu up.
I (421) spiram: SPI SRAM memory test OK
W (422) rtcinit: calibration efuse version does not match, set default version: 0

I (434) cpu_start: Pro cpu start user code
I (434) cpu_start: cpu freq: 240000000
I (434) cpu_start: Application information:
I (437) cpu_start: Project name:     lcd_demo
I (442) cpu_start: App version:      1
I (446) cpu_start: Compile time:     Jan  5 2022 20:08:30
I (452) cpu_start: ELF file SHA256:  156ab7d9ddb43dc3...
I (458) cpu_start: ESP-IDF:          v4.4-beta1-183-gf23dcd3555-dirt
I (465) heap_init: Initializing. RAM available for dynamic allocation:
I (472) heap_init: At 3FC9A338 len 00045CC8 (279 KiB): D/IRAM
I (479) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (485) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (492) spiram: Adding pool of 2048K of external SPI memory to heap allocator
I (500) spi_flash: detected chip: winbond
I (504) spi_flash: flash io: qio
I (509) sleep: Configure to isolate all GPIO pins in sleep state
I (515) sleep: Enable automatic switching of GPIO sleep configuration
I (522) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (543) spiram: Reserving pool of 8K of internal memory for DMA/internal allocations
I (543) i2c_bus: i2c0 bus inited
I (553) tca9554: tca9554 init ok
I (573) bsp_lcd: Initialize LCD Intel 8080 bus
I (573) bsp_lcd: Install LCD driver of rm68120
I (573) gpio: GPIO[18]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (713) rm68120: LCD=800x480 dir=0 xgap=0 ygap=0
I (713) rm68120: madctl=0x60 colmod=0x55
I (713) lcd_debug: 800x480
I (753) UVC_STREAM: UVC Streaming Config Succeed
I (803) UVC_STREAM: UVC Streaming Starting
I (833) UVC_STREAM: Port=1 init succeed
I (833) UVC_STREAM: Waitting USB Connection
I (1083) UVC_STREAM: line 354 HCD_PORT_EVENT_CONNECTION
I (1083) UVC_STREAM: Resetting Port
I (1143) UVC_STREAM: Setting Port FIFO
I (1143) UVC_STREAM: Getting Port Speed
I (1143) UVC_STREAM: Port speed = 1
I (1143) UVC_STREAM: USB Speed: full-speed
I (1143) UVC_STREAM: Set Device Addr = 1
I (1153) UVC_STREAM: Set Device Addr Done
I (1153) UVC_STREAM: Set Device Configuration = 1
I (1163) UVC_STREAM: Set Device Configuration Done
I (1163) UVC_STREAM: SET_CUR Probe
I (1173) UVC_STREAM: SET_CUR Probe Done
I (1173) UVC_STREAM: GET_CUR Probe
bmHint: 0001
bFormatIndex: 1
bFrameIndex: 4
dwFrameInterval: 666666
wKeyFrameRate: 0
wPFrameRate: 0
wCompQuality: 0
wCompWindowSize: 0
wDelay: 0
dwMaxVideoFrameSize: 614400
dwMaxPayloadTransferSize: 1536
dwClockFrequency: 0
bmFramingInfo: 0
bPreferredVersion: 0
bMinVersion: 0
bMaxVersion: 0
bInterfaceNumber: 1
I (1203) UVC_STREAM: GET_CUR Probe Done, actual_num_bytes:64
I (1213) UVC_STREAM: SET_CUR COMMIT
I (1223) UVC_STREAM: SET_CUR COMMIT Done
I (1223) UVC_STREAM: Set Device Interface = 1, Alt = 1
I (1223) UVC_STREAM: Set Device Interface Done
I (1233) UVC_STREAM: Sample processing task started
I (1283) UVC_STREAM: Camera Start Streaming

**Comment by leeebo** [comment]
It is usually caused by the incorrect configuration or the camera itself is not supported.

The [latest commits](https://github.com/espressif/esp-iot-solution/commit/3505a91fe2a25054d4e5a14e2363ca953933fae2) of uvc_stream can help print the camera's full speed descriptors (may differ from your posted version), please try to find the real configs of your camera. BTW. IDF should also be updated to the latest release/v4.4, [these new commits](https://github.com/espressif/esp-idf/commit/2e8df440c11172175a544608e139512da7997404) must be included
