### ISSUE TITLE
"usb_cdc_4g_module+ip_napt_enable" not work for camera to connect

### ISSUE THREAD

**Issue by achao1104** [espressif/esp-iot-solution#159]
Hello,
My idf is 4.3.1 and module is esp32s2. I am running the usb_cdc_4g_module sample. It works well, both my mobile and my PC can connect esp32s2 which actually works as wifi ap.
One third party camera can connect the esp32s2-wifi-ap as well, and even the camera can upload video to cloud smoothly.
If my mobile connects the same esp32s2-wifi-ap, my mobile can operate, open and play the live video of the camera smoothly.
The problem is that if my mobile connects LTE network or another wifi router, my mobile can not connect the camera and play live video, I guess there might be some issues related to NAT or setting of wifi ap, but don't know how to solve.
Please help!
Thanks,
Peter

**Comment by leeebo** [comment]
@achao1104 ` the camera can upload video to cloud smoothly.` but can not transfer images to your phone(connects LTE) through internet ?

Don't really know the network communication strategy of this Camera. Could you replace `your mobile` with a PC installed Wireshark to capture net packets to find issues
