### ISSUE TITLE
Updating LVGL to actual version (8.1)

### ISSUE THREAD

**Issue by madenlord** [espressif/esp-iot-solution#162]
I'm currently using the esp-iot-solution for one of my projects, and I would like to use some LVGL features that are only available on the 8.1 version, such as menus or scatter charts, etc (the esp-iot-solution lvgl version is 7.5.0). 

Is there any way to easily update the LVGL version of the esp-iot-solution? If there is, how can I do it and make the lvgl_gui work?

Thank you very much!

**Comment by sukesh-ak** [comment]
You can check this sample. 
https://github.com/sukesh-ak/LVGL8-WT32-SC01-IDF

**Comment by leeebo** [comment]
Please try with [esp_lvgl_port](https://components.espressif.com/components/espressif/esp_lvgl_port), with based on LVGL v8 now
