### ISSUE TITLE
Question about Si4432 driver api

### ISSUE THREAD

**Issue by XiotSamuel** [espressif/esp-iot-solution#175]
## Problem Description

Hi I am implementing a Si4432 with RH22. Any driver/source code I can refer to? I cannot found any esp driver, and I dont want to use the arduino one.

**Comment by TDA-2030** [comment]
Sorry, Espressif seems don't provide the driver of this chip. Maybe you can migrate it from the driver of other MCUs.

**Comment by nopnop2002** [comment]
@XiotSamuel 

SI4432 ISM Transceiver driver for esp-idf.

https://github.com/nopnop2002/esp-idf-si4432
