### ISSUE TITLE
LED Indicator Custom Blink Types (AEGHB-62)

### ISSUE THREAD

**Issue by digimatt22** [espressif/esp-iot-solution#176]
Following the instructions provided in the [https://docs.espressif.com/projects/espressif-esp-iot-solution/en/latest/display/led_indicator.html](documentation) I have attempted add a custom blink type.  In this instance I have used the exact code as provided in the documentation but when I compile I am given the error that there is a redeclaration of BLINK_MAX.  Is there an example I can reference that will provide clarification on the step "After defining a blink type, you need to add its corresponding enumeration member to led_indicator_blink_type_t"?

Additionally after calling led_indicator_stop, if no blink type is assigned to the handle what is the state of the GPIO?  Can this be controlled using the handle or do we have to use the standard GPIO methods?

**Comment by lijunru-hub** [comment]
The LED Indicator already updated. Please refer: https://docs.espressif.com/projects/espressif-esp-iot-solution/en/latest/display/led_indicator.html
