### ISSUE TITLE
spi_bus 如何完成先发后读

### ISSUE THREAD

**Issue by ghost** [espressif/esp-iot-solution#177]
目前好像完成不了类似rt_err_t rt_spi_send_then_recv的功能

先发送后接收数据

本函数适合从SPI外设中读取一块数据，本函数中会先发送一些数据（如命令和地址），然后再接收指定长度的数据。此函数等同于调用rt_spi_transfer_message()传输2条消息。

参数
device	SPI 从设备句柄
send_buf	发送缓冲区数据指针
send_length	发送缓冲区数据字节数
recv_buf	接收缓冲区数据指针，spi 是全双工的，支持同时收发
recv_length	接收缓冲区数据字节数
返回
RT_EOK 成功，-RT_EIO 失败。

**Comment by TDA-2030** [comment]
你需要的先发送后接收数据应该启动两次SPI传输就可以完成了
