### ISSUE TITLE
Conflict between iot_lcd.cpp and SPI SDCARD.

### ISSUE THREAD

**Issue by yihua-wang** [espressif/esp-iot-solution#18]
HI，the engineer who makes the  “iot_lcd. cpp”.
I am using “iot_lcd. cpp” on the M5Stack. 
Because the LCD and SD SPI of M5Stack are reused.
First of all , I used the APIS of LCD, and second I initialize the SD APIS. It's ok for me to read and write some files by SD APIS.
Finally, after using SD APIS, all the LCD APIS are failed.
added: 
My LCD spi is HSPI, using dma channel 1.
My SD spi is VSPI, using dma channel 2.

**Comment by InfiniteYuan1** [comment]
Thank you. I hope you can help us reproduce it.

**Comment by InfiniteYuan1** [comment]
Can you provide a complete reproduction process?

**Comment by InfiniteYuan1** [comment]
Please follow the link to this issue.[#1597](https://github.com/espressif/esp-idf/issues/1597)

**Comment by Xiehanxin** [comment]
@WangYifa  hello, If your issue is now resolved, can you please close the issue. Thank you.
