### ISSUE TITLE
set-targrt error: Failed to resolve component 'usb'.

### ISSUE THREAD

**Issue by HaochengZheng** [espressif/esp-iot-solution#180]
## Environment

- Development Kit:      none
- Module or chip used:  ESP32-s2 (Adafruit ESP32-s2 TFT feather)
- IDF version (run ``git describe --tags`` to find it): v4.3.2
- Build System:         CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):GNU C++14 (crosstool-NG esp-2021r2) version 8.4.0 (xtensa-esp32s2-elf); compiled by GNU C version 6.3.0 20170516, GMP version 6.2.0, MPFR version 4.0.2, MPC version 1.1.0, isl version isl-0.19-GMP

- Operating System:    Windows
- Power Supply:         USB

## Problem Description

I tried to set-targt for usb_camera_lcd_display example, but generate the error. I tried to do the same thing in ESP IDF v 4.4 and it is successful. 
CMake Error at C:/Espressif/frameworks/esp-idf-v4.3.2/tools/cmake/build.cmake:191 (message):
  Failed to resolve component 'usb'.
Call Stack (most recent call first):
  C:/Espressif/frameworks/esp-idf-v4.3.2/tools/cmake/build.cmake:217 (__build_resolve_and_add_req)
  C:/Espressif/frameworks/esp-idf-v4.3.2/tools/cmake/build.cmake:441 (__build_expand_requirements)
  C:/Espressif/frameworks/esp-idf-v4.3.2/tools/cmake/project.cmake:399 (idf_build_process)
  CMakeLists.txt:20 (project)

### Expected Behavior
Successful set-target

### Steps to repropduce

1. idf.py set-target esp32s2

**Comment by TDA-2030** [comment]
Maybe you can try deleting the `build` directory and `sdkconfig` file.
