### ISSUE TITLE
board_esp32s3_usb_otg_ev.c:18:10: fatal error: esp_adc_cal.h: No such file or directory

### ISSUE THREAD

**Issue by github150620** [espressif/esp-iot-solution#189]
Branch: usb/add_usb_solutions
Example: ~/esp/esp-iot-solution/examples/usb/device/usb_msc_wireless_disk
Target: esp32s3

```
idf.py set-target esp32s3
idf.py menuconfig
idf.py build
...
~/esp/esp-iot-solution/example/common_components/boards/esp32s3_usb_otg_ev/board_esp32s3_usb_otg_ev.c:18:10 fatal error: esp_adc_cal.h: No such file or directory
 #include "esp_adc_cal.h"
           ^~~~~~~~~~
...
```

When I use target 'esp32s2', it works well. It seems the example 'usb_msc_wireless_disk' is designed for ESP32S3, but it only works well on ESP32S2.

**Comment by leeebo** [comment]
@github150620 Bug from the esp32s3-usb-otg code in boards component, you can configure Menuconfig -> Board Options -> Choose -> ESP32S2 Saola to work around, will fix it soon.
