### ISSUE TITLE
[enhancement request]i2s_lcd_esp32s3_driver.c

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-iot-solution#194]
There is components/bus/i2s_lcd_esp32_driver.c and components/busi2s_lcd_esp32s2_driver.c.
But there isn't components/bus/i2s_lcd_esp32s3_driver.c.

**Comment by TDA-2030** [comment]
https://github.com/espressif/esp-iot-solution/blob/master/components/bus/8080_lcd_esp32s3.c is what you need. S3 implements the 8080 interface via peripheral `LCD_CAM` rather than `I2S`, so the name of the c file is different.
