### ISSUE TITLE
What model camera should I buy for USB Host Camera experiment? (AEGHB-70)

### ISSUE THREAD

**Issue by ziv2013** [espressif/esp-iot-solution#203]
Hi,

I have tried 2 USB cameras, but none of them can work with examples/usb/host/usb_camera_wifi_transfer.

Could you tell me the USB model you used for this experiment? I'd like to buy a same one.

Thanks,

Z.t

**Comment by nopnop2002** [comment]
hi @ziv2013 


here is helpful

https://github.com/nopnop2002/esp-idf-video-streaming/issues

**Comment by leeebo** [comment]
@ziv2013 Please refer the usb camera guide for the limitations https://docs.espressif.com/projects/espressif-esp-iot-solution/en/latest/usb/usb_stream.html#usb-stream-user-guide.

And the [new USB camera](https://github.com/espressif/esp-iot-solution/tree/master/components/usb/usb_stream) driver will parsing the USB descriptor to judge if the camera can be supported

**Comment by ziv2013** [comment]
Thanks for your guide.

**Comment by leeebo** [comment]
@ziv2013 We now have [ESP32-S3-LCD-EV-Board (with a 720P USB Camera)](https://m.tb.cn/h.UDepUJP?tk=TpmvdLBsNKX) for users quick start with USB cameras development

If you are a commercial user and need to purchase related cameras in bulk, please contact [sales@espressif.com](mailto:sales@espressif.com)
