### ISSUE TITLE
Not able to compile the aws_iot_demo

### ISSUE THREAD

**Issue by jgrocha** [espressif/esp-iot-solution#22]
## Environment

- Development Kit: ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): ?
- Module or chip used:  ESP32D0WDQ6 (revision 1)
- IDF version: v3.3-dev-206-g0d7f2d77c
- Build System: make
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 5.2.0
- Operating System: Linux
- Power Supply: USB

## Problem Description

I'm not able to compile  `esp-iot-solution/examples/aws_iot_demo`. `make` fails with `fatal error: iot_lcd.h: No such file or directory`

### Expected Behavior

The example should be able compile, but here is something wrong or missing in my setup.

There is no `iot_lcd.h` in `main/include`. The `iot_lcd.h` is locate in `/esp-iot-solution/components/spi_devices/lcd/include/iot_lcd.h`. 

Should I add some definition to the Makefile? Should I install components under `aws_iot_demo` folder?

### Actual Behavior

```
jgr@zoe:~/dev/esp/esp-iot-solution/examples/aws_iot_demo$ make
CXX build/main/aws_iot_lcd.o
/home/jgr/dev/esp/esp-iot-solution/examples/aws_iot_demo/main/aws_iot_lcd.cpp:14:21: fatal error: iot_lcd.h: No such file or directory
```

### Steps to repropduce

```
cd esp-iot-solution/examples/aws_iot_demo
make menuconfig
make
```

### Other examples

The `oled_screen_module` compiles and runs perfectly!

```
cd esp-iot-solution/examples/oled_screen_module
make menuconfig
make flash monitor
```

**Comment by costaud** [comment]
I think this has been fixed now.
