### ISSUE TITLE
Integration of USB PPPoS + USB AT command integration (AEGHB-71)

### ISSUE THREAD

**Issue by abhi-ratnman** [espressif/esp-iot-solution#222]
Hello, I have tested both the PPPoS over USB and AT commands over USB using the examples provided. Now i wanted to ask that, if i want to do both using the same USB port is it possible? What are the thing i will need to take care while integration of both? Do i need to turn off the data mode of PPPoS before sending AT commands? 

Also are both the examples thread safe?

@leeebo your support will be highly appreciated

**Comment by ankit-thealchemist** [comment]
yes mostly is it natively thread safe?

**Comment by leeebo** [comment]
@abhi-ratnman  Yes using same USB port with two modes is possible. 

For some modems with only one modem interface(support AT+PPP), you need to using command like `+++` to change to AT mode, then using `ATO` back to PPP mode. 

While some modems support both modem interface and a secondary AT interface, you can using AT and PPP at the same time.

**Comment by leeebo** [comment]
@abhi-ratnman  Yes using same USB port with two modes is possible. 

For some modems with only one modem interface(support AT+PPP), you need to using command like `+++` to change to AT mode, then using `ATO` back to PPP mode. 

While some modems support both modem interface and a secondary AT interface, you can using AT and PPP at the same time.

**Comment by leeebo** [comment]
Please refer: https://github.com/espressif/esp-iot-solution/tree/usb/add_usb_solutions/examples/usb/host/usb_cdc_4g_module#hardware-requirement

**Comment by abhi-ratnman** [comment]
@leeebo we're using sim7672x module. So it is supported by the example

**Comment by ankit-thealchemist** [comment]
Is usb cdc host library thread safe? We are most probably sending the commands from different threads.

**Comment by leeebo** [comment]
> Is usb cdc host library thread safe? We are most probably sending the commands from different threads.

USB CDC host library is thread-safe, but `dce_common_commands` API is not thread-safe, you need to add an external mutex to `sending->waiting->handling` from different threads

**Comment by ankit-thealchemist** [comment]
@leeebo Thanks for quick reply!
we are mostly sending the AT commands over the cdc, which we tested using the example usb cdc host. 
https://github.com/espressif/esp-iot-solution/blob/usb/add_usb_solutions/examples/usb/host/usb_cdc_basic/main/usb_cdc_basic_main.c

**Comment by ankit-thealchemist** [comment]
> @abhi-ratnman Yes using same USB port with two modes is possible.
> 
> For some modems with only one modem interface(support AT+PPP), you need to using command like `+++` to change to AT mode, then using `ATO` back to PPP mode.
> 
> While some modems support both modem interface and a secondary AT interface, you can using AT and PPP at the same time.

@leeebo Thanks for the help!!

Could you give the example, how to route the at commands to the secondary AT interface, say endpoints are IN 0x82 and out 0x0C for secondary at interface

**Comment by abhi-ratnman** [comment]
hi @leeebo any update?

**Comment by leeebo** [comment]
@abhi-ratnman @ankit-thealchemist For the new iot_usbh_modem driver, you can config it through menuconfig https://github.com/espressif/esp-iot-solution/blob/master/components/usb/iot_usbh_modem/Kconfig#L77
