### ISSUE TITLE
使用usb_dongle 蓝牙功能 linux bluez报错Failed to register advertisement: org.bluez.Error.Failed 

### ISSUE THREAD

**Issue by yuandonglp** [espressif/esp-iot-solution#223]
esp-iot-solution/examples/usb/device/usb_dongle
Component config->TinyUSB Stack配置中关闭了cdc串口配置，打开了Bluetooth Host Class配置，打开了ECM配置然后 Component config->Bluetooth中选择Bluetooth controller中的Bluetooth Host（Bluedroid - Dual-mode）模式，其他为默认值
然后编译程序烧写至ESP32S3中，在linux主机上hciconfig 可以看到蓝牙网卡设备，使用linux中的bluetoothctl工具来对esp32s3蓝牙进行操作，在输入advertise on打开esp32s3的蓝牙广播时报了Failed to register advertisement: org.bluez.Error.Failed 这个错误，同时也无法发现esp32s3这个蓝牙设备。

**Comment by tswen** [comment]
Hi，USB-Dongle 方案中蓝牙目前只可以使用 controller，可以实现 linux 主机上发现别的蓝牙设备，但是 ESP32-S3 不属于一个蓝牙设备。
