### ISSUE TITLE
Compile report error when i set the single NIMBLE mode on ble_ota example (AEGHB-65)

### ISSUE THREAD

**Issue by Rainbow-Cai** [espressif/esp-iot-solution#249]
SoC: ESP32-S3

IDF version : release/v4.4

Question：

Hi @IshaESP  When I was testing "[esp-iot-solution/examples/bluetooth/ble_ota](https://github.com/espressif/esp-iot-solution/tree/master/examples/bluetooth/ble_ota)" example on master version , after I set the single NIMBLE mode in menuconfig, the compilation error , could you please check it?

**Comment by IshaESP** [comment]
Hi @Rainbow-Cai ,
The compilation error is due to IDF version. Can you try this [patch.zip](https://github.com/espressif/esp-iot-solution/files/10697511/patch.zip)? 
A MR is raised internally for this fix.

Thank You.
