### ISSUE TITLE
esp32s3 usb_cdc_4g_module with EC200U-EU (AEGHB-118)

### ISSUE THREAD

**Issue by sjleesj** [espressif/esp-iot-solution#255]
Test esp32s3+EC200U-EU get below error，I haved try change the end Endpoint with  0x81-0x01, 0x82-0x01, 0x83-0x02,  0x84-0x02, 0x85-0x03, 0x86-0x04, 0x87-0x05, 0x88-0x06, 0x89-0x07, 0x8a-0x07, 0x8b-0x08, all get error; Please help analyze the reason!

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x17c4
load:0x403c9700,len:0xe78
load:0x403cc700,len:0x310c
entry 0x403c9980
I (25) boot: ESP-IDF v4.4.4-dirty 2nd stage bootloader
I (25) boot: compile time 23:49:09
I (25) boot: chip revision: v0.1
I (27) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (34) qio_mode: Enabling default flash chip QIO
I (40) boot.esp32s3: Boot SPI Speed : 80MHz
I (44) boot.esp32s3: SPI Mode       : QIO
I (49) boot.esp32s3: SPI Flash Size : 8MB
I (54) boot: Enabling RNG early entropy source...
I (59) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (70) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (78) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (85) boot:  2 factory          factory app      00 00 00010000 00100000
I (92) boot:  3 storage          Unknown data     01 82 00110000 00100000
I (100) boot: End of partition table
I (104) boot_comm: chip revision: 1, min. application chip revision: 0
I (111) esp_image: segment 0: paddr=00010020 vaddr=3c0a0020 size=21268h (135784) map
I (140) esp_image: segment 1: paddr=00031290 vaddr=3fc99a20 size=0443ch ( 17468) load
I (144) esp_image: segment 2: paddr=000356d4 vaddr=40374000 size=0a944h ( 43332) load
I (155) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=987b4h (624564) map
I (250) esp_image: segment 4: paddr=000d87dc vaddr=4037e944 size=0b0d4h ( 45268) load
I (267) boot: Loaded app from partition at offset 0x10000
I (267) boot: Disabling RNG early entropy source...
I (279) cpu_start: Pro cpu up.
I (279) cpu_start: Starting app cpu, entry point is 0x40375678
0x40375678: call_start_cpu1 at D:/idf/Espressif/frameworks/esp-idf-v4.4.4/components/esp_system/port/cpu_start.c:148

I (0) cpu_start: App cpu up.
I (293) cpu_start: Pro cpu start user code
I (293) cpu_start: cpu freq: 240000000
I (293) cpu_start: Application information:
I (295) cpu_start: Project name:     cdc_4g
I (300) cpu_start: App version:      1
I (305) cpu_start: Compile time:     Mar 31 2023 15:17:13
I (311) cpu_start: ELF file SHA256:  d1cef5d9f5f8e444...
I (317) cpu_start: ESP-IDF:          v4.4.4-dirty
I (322) heap_init: Initializing. RAM available for dynamic allocation:
I (329) heap_init: At 3FCA1820 len 00047EF0 (287 KiB): D/IRAM
I (336) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
I (343) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (349) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (355) spi_flash: detected chip: gd
I (359) spi_flash: flash io: qio
W (363) spi_flash: Detected size(16384k) larger than the size in the binary image header(8192k). Using the size in the binary image header.
I (377) sleep: Configure to isolate all GPIO pins in sleep state
I (383) sleep: Enable automatic switching of GPIO sleep configuration
I (390) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (3431) 4g_main: ====================================
I (3431) 4g_main:      ESP 4G Cat.1 Wi-Fi Router
I (3431) 4g_main: ====================================
W (3437) modem_board: Force reset modem
I (3441) gpio: GPIO[0]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
W (3451) modem_board: Resetting modem using io=0, level=0
W (3657) modem_board: Waiting for modem initialize ready
I (8687) ESP_USBH: USB Port=1 init succeed, fifo strategy=0
I (8737) USB_HCDC: CDC task start
I (8737) ESP_USBH: usb port start succeed
I (8737) USB_HCDC: usb driver install succeed
I (8740) USB_HCDC: Waiting CDC Device Connection
I (8745) ESP_USBH: USB Processing Start
I (8749) ESP_USBH: Waiting USB Connection
I (8754) ESP_USBH: Port power: ON Succeed
I (10313) ESP_USBH: line 144 PORT_EVENT_CONNECTION
I (10413) ESP_USBH: Resetting Port
I (10473) ESP_USBH: Port reset succeed
I (10473) ESP_USBH: Getting Port Speed
I (10473) ESP_USBH: USB Speed: full-speed
I (10476) ESP_USBH: Pipe init succeed, addr: 00
I (10481) ESP_USBH: Set Device Addr = 1
I (10486) ESP_USBH: Set Device Addr Done
I (10490) ESP_USBH: get device desc
I (10494) ESP_USBH: get device desc, actual_num_bytes:26
*** Device descriptor ***
bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0x0
bDeviceSubClass 0x0
bDeviceProtocol 0x0
bMaxPacketSize0 64
idVendor 0x1782
idProduct 0x4d12
bcdDevice 3.10
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
I (10523) ESP_USBH: get short config desc
I (10528) ESP_USBH: get config desc, actual_num_bytes:16
I (10534) ESP_USBH: get full config desc
I (10539) ESP_USBH: get full config desc, actual_num_bytes:40
*** Configuration descriptor ***
bLength 9
bDescriptorType 2
wTotalLength 32
bNumInterfaces 1
bConfigurationValue 1
iConfiguration 0
bmAttributes 0xe0
bMaxPower 400mA
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 0
        bAlternateSetting 0
        bNumEndpoints 2
        bInterfaceClass 0xff
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 4
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x81   EP 1 IN
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x1    EP 1 OUT
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
I (10606) ESP_USBH: Set Device Configuration = 1
I (10612) ESP_USBH: Set Device Configuration Done
I (10617) ESP_USBH: Pipe init succeed, addr: 84
I (10622) ESP_USBH: Pipe init succeed, addr: 02
I (10628) USB_HCDC: CDC Device Connected
I (10632) esp-modem: --------- Modem PreDefined Info ------------------
I (10639) esp-modem: Model: User Defined
I (10644) esp-modem: Modem itf: IN Addr:0x84, OUT Addr:0x02
I (10650) esp-modem: ----------------------------------------------------
I (10658) USB_HCDC: rx0 flush -0 = 0
W (10662) USB_HCDC: Itf:0 ep: 0x84 PIPE_EVENT_ERROR_XFER
W (10668) USB_HCDC: Itf:0 ep: 0x02 PIPE_EVENT_ERROR_XFER
I (10674) modem_board: DTE reconnect, reconnecting ...

W (11063) ESP_USBH: line 148 PORT_EVENT_DISCONNECTION
I (11063) ESP_USBH: hcd port state = 7
I (11064) USB_HCDC: CDC task Reset
W (11066) ESP_USBH: pipe=0x3fcf75a0 clear failed
W (11072) USB_HCDC: in pipe flush failed
I (11076) ESP_USBH: esp_usbh_pipe_deinit: pipe state = 1
I (11082) ESP_USBH: Pipe deinit succeed, addr: 84
W (11088) ESP_USBH: pipe=0x3fcf7654 clear failed
W (11093) USB_HCDC: out pipe flush failed
I (11097) ESP_USBH: esp_usbh_pipe_deinit: pipe state = 1
I (11104) ESP_USBH: Pipe deinit succeed, addr: 02
I (11109) USB_HCDC: rx0 flush -0 = 0
I (11113) USB_HCDC: tx0 flush -0 = 0
W (11117) ESP_USBH: Resetting USB Driver
W (11122) ESP_USBH: Resetting default pipe
W (11227) ESP_USBH: pipe=0x3fceed90 clear failed
I (11227) ESP_USBH: esp_usbh_pipe_deinit: pipe state = 1
I (11227) ESP_USBH: Pipe deinit succeed, addr: 00
I (11233) ESP_USBH: hcd recovering
I (11237) ESP_USBH: Port power: ON Succeed
I (11342) ESP_USBH: Waiting USB Connection
I (11592) ESP_USBH: line 144 PORT_EVENT_CONNECTION
I (11680) modem_board: reconnect after 5s...
I (11692) ESP_USBH: Resetting Port
I (11752) ESP_USBH: Port reset succeed
I (11752) ESP_USBH: Getting Port Speed
I (11752) ESP_USBH: USB Speed: full-speed
I (11755) ESP_USBH: Pipe init succeed, addr: 00
I (11760) ESP_USBH: Set Device Addr = 1
I (11765) ESP_USBH: Set Device Addr Done
I (11769) ESP_USBH: get device desc
I (11773) ESP_USBH: get device desc, actual_num_bytes:26
*** Device descriptor ***
bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0x0
bDeviceSubClass 0x0
bDeviceProtocol 0x0
bMaxPacketSize0 64
idVendor 0x2c7c
idProduct 0x901
bcdDevice 3.10
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
I (11802) ESP_USBH: get short config desc
I (11807) ESP_USBH: get config desc, actual_num_bytes:16
I (11813) ESP_USBH: get full config desc
I (11818) ESP_USBH: get full config desc, actual_num_bytes:271
*** Configuration descriptor ***
bLength 9
bDescriptorType 2
wTotalLength 263
bNumInterfaces 9
bConfigurationValue 1
iConfiguration 0
bmAttributes 0xe0
bMaxPower 400mA
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 0
        bAlternateSetting 0
        bNumEndpoints 1
        bInterfaceClass 0x2
        bInterfaceSubClass 0x6
        bInterfaceProtocol 0x0
        iInterface 6
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x81   EP 1 IN
                bmAttributes 0x3        INT
                wMaxPacketSize 16
                bInterval 32
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 1
        bAlternateSetting 0
        bNumEndpoints 0
        bInterfaceClass 0xa
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 0
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 1
        bAlternateSetting 1
        bNumEndpoints 2
        bInterfaceClass 0xa
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 5
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x82   EP 2 IN
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x1    EP 1 OUT
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 2
        bAlternateSetting 0
        bNumEndpoints 3
        bInterfaceClass 0xff
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 8
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x84   EP 4 IN
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x2    EP 2 OUT
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x83   EP 3 IN
                bmAttributes 0x3        INT
                wMaxPacketSize 64
                bInterval 32
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 3
        bAlternateSetting 0
        bNumEndpoints 2
        bInterfaceClass 0xff
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 8
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x85   EP 5 IN
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x3    EP 3 OUT
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 4
        bAlternateSetting 0
        bNumEndpoints 2
        bInterfaceClass 0xff
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 8
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x86   EP 6 IN
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x4    EP 4 OUT
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 5
        bAlternateSetting 0
        bNumEndpoints 2
        bInterfaceClass 0xff
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 8
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x87   EP 7 IN
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x5    EP 5 OUT
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 6
        bAlternateSetting 0
        bNumEndpoints 2
        bInterfaceClass 0xff
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 8
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x88   EP 8 IN
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x6    EP 6 OUT
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 7
        bAlternateSetting 0
        bNumEndpoints 3
        bInterfaceClass 0xff
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 8
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x8a   EP 10 IN
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x7    EP 7 OUT
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x89   EP 9 IN
                bmAttributes 0x3        INT
                wMaxPacketSize 64
                bInterval 32
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 8
        bAlternateSetting 0
        bNumEndpoints 2
        bInterfaceClass 0xff
        bInterfaceSubClass 0x0
        bInterfaceProtocol 0x0
        iInterface 8
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x8b   EP 11 IN
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x8    EP 8 OUT
                bmAttributes 0x2        BULK
                wMaxPacketSize 64
                bInterval 0
I (12286) ESP_USBH: Set Device Configuration = 1
I (12291) ESP_USBH: Set Device Configuration Done
I (12296) ESP_USBH: Pipe init succeed, addr: 84
I (12302) ESP_USBH: Pipe init succeed, addr: 02
I (12307) modem_board: DTE reconnect, reconnecting ...

I (13313) modem_board: reconnect after 5s...
I (14313) modem_board: reconnect after 4s...
I (15313) modem_board: reconnect after 3s...
I (16313) modem_board: reconnect after 2s...
I (17313) modem_board: reconnect after 1s...
I (17313) modem_board: Modem state STAGE_SYNC, Start
W (17359) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+IFC=0,0
...failed
E (17359) modem_board: modem_board_start_up(245): set_flow_ctrl failed
I (17364) modem_board: Modem state STAGE_SYNC, Start
W (17415) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+IFC=0,0
...failed
E (17415) modem_board: modem_board_start_up(245): set_flow_ctrl failed
I (17420) modem_board: Modem state STAGE_SYNC, Start
W (17471) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+IFC=0,0
...failed
E (17471) modem_board: modem_board_start_up(245): set_flow_ctrl failed
I (17476) modem_board: Modem state STAGE_SYNC, Start
W (17527) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+IFC=0,0
...failed
E (17527) modem_board: modem_board_start_up(245): set_flow_ctrl failed
I (17532) modem_board: Modem state STAGE_SYNC, Start
W (17583) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+IFC=0,0
...failed
E (17583) modem_board: modem_board_start_up(245): set_flow_ctrl failed
I (17588) modem_board: Modem state STAGE_SYNC, Start
W (17639) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+IFC=0,0

**Comment by sjleesj** [comment]
the Endpoint is  0x7 OUT, 0x8a  IN,    and then also got error:
I (25086) ESP_USBH: Set Device Configuration = 1
I (25091) ESP_USBH: Set Device Configuration Done
I (25096) ESP_USBH: Pipe init succeed, addr: 8A
I (25102) ESP_USBH: Pipe init succeed, addr: 07
I (25107) modem_board: DTE reconnect, reconnecting ...

I (26113) modem_board: reconnect after 5s...
I (27113) modem_board: reconnect after 4s...
I (28113) modem_board: reconnect after 3s...
I (29113) modem_board: reconnect after 2s...
I (30113) modem_board: reconnect after 1s...
I (30113) modem_board: Modem state STAGE_SYNC, Start
W (30159) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+IFC=0,0
...failed
E (30159) modem_board: modem_board_start_up(245): set_flow_ctrl failed
I (30164) modem_board: Modem state STAGE_SYNC, Start
W (30215) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+IFC=0,0
...failed
E (30215) modem_board: modem_board_start_up(245): set_flow_ctrl failed
I (30220) modem_board: Modem state STAGE_SYNC, Start
W (30271) esp_modem_dce: esp_modem_dce_generic_command(35): Command:AT+IFC=0,0
...failed
E (30271) modem_board: modem_board_start_up(245): set_flow_ctrl failed
I (30276) modem_board: Modem state STAGE_SYNC, Start


but when I Block this code，it works;
![111](https://user-images.githubusercontent.com/22888139/229188635-5fec3894-86d9-40e1-93ff-8b1bc54a9248.jpg)


![屏幕截图 2023-04-01 012310](https://user-images.githubusercontent.com/22888139/229188441-fc4d4dac-e67d-4b53-a903-d8bce99b4466.jpg)

**Comment by leeebo** [comment]
@sjleesj Thanks for your report. Set `echo behavior` is a very common AT command, but seems the module EC200U does not support it (or they use a custom format?), would you please help check the modem's specification to confirm it?

**Comment by sjleesj** [comment]
The module manufacturer provided these specifications

[EC200U Mini PCle.zip](https://github.com/espressif/esp-iot-solution/files/11183804/EC200U.Mini.PCle.zip)
[Quectel_ECx00U&EGx00U系列_Linux_USB驱动_用户指导_V1.0.0_Preliminary_20210310.pdf](https://github.com/espressif/esp-iot-solution/files/11183805/Quectel_ECx00U.EGx00U._Linux_USB._._V1.0.0_Preliminary_20210310.pdf)

**Comment by leeebo** [comment]
@sjleesj The module may not support flow control command, according to the module's AT manual, we should check whether it can be configured before issuing the configuration command... Will fix it, thanks for report

![image](https://user-images.githubusercontent.com/16922815/230905090-fb4116e9-75aa-4e18-8bc6-585ecf571616.png)
