### ISSUE TITLE
Camera NT99141无画面，OV3660分辨率设置失败。OV2640正常 (AEGHB-122)

### ISSUE THREAD

**Issue by 919643218** [espressif/esp-iot-solution#256]
## Environment

- Development Kit:      [none]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROVER-B]
- IDF version (run ``git describe --tags`` to find it): 
    esp-idf-V4.4.4
- Build System:         [Make|CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch5) 8.4.0
- Operating System:     [Windows]
- Power Supply:         [USB|external 5V]

## Problem Description

使用example/camera/video_stream_server例程编译烧录后，使用OV2640正常使用。更换摄像头OV3660，无法启动，日志显示为分辨设置错误。更换摄像头为NT99141，初始化通过后，无法显示画面。

### Expected Behavior
画面都正常显示

### Actual Behavior
NT99141无法显示画面。OV3660无法启动
### Steps to repropduce

1. step1
2. ...

// It helps if you attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{
    
}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

I (1408) wifi:pm start, type: 0[2023-03-31 11:29:42.839]
[2023-03-31 11:29:42.839]
[0;32mI (1418) camera: Detected camera at address=0x3c[0m[2023-03-31 11:29:42.843]
[0;32mI (1418) camera: Detected OV3660 camera[0m[2023-03-31 11:29:42.847]
[0;32mI (1418) camera: Camera PID=0x3660 VER=0x00 MIDL=0x00 MIDH=0x00[0m[2023-03-31 11:29:42.855]
I (1478) wifi:AP's beacon interval = 102400 us, DTIM period = 3[2023-03-31 11:29:42.916]
[0;31mE (1578) sccb: W [518b]=e0 0 fail[2023-03-31 11:29:43.015]
[0m[2023-03-31 11:29:43.015]
[0;32mI (1578) cam_hal: buffer_size: 32768, half_buffer_size: 4096, node_buffer_size: 2048, node_cnt: 16, total_cnt: 23[0m[2023-03-31 11:29:43.015]
[0;32mI (1588) cam_hal: Allocating 96000 Byte frame buffer in PSRAM[0m[2023-03-31 11:29:43.037]
[0;32mI (1588) cam_hal: Allocating 96000 Byte frame buffer in PSRAM[0m[2023-03-31 11:29:43.037]
[0;32mI (1598) cam_hal: cam config ok[0m[2023-03-31 11:29:43.037]
[0;31mE (1608) sccb: W [3808]=03 1 fail[2023-03-31 11:29:43.037]
[0m[2023-03-31 11:29:43.037]
[0;31mE (1608) ov3660: Setting framesize to: 800x600 failed[0m[2023-03-31 11:29:43.037]
[0;31mE (1608) camera: Failed to set frame size[0m[2023-03-31 11:29:43.050]
[0;31mE (1618) who_camera: Camera init failed with error 0x20002[0m[2023-03-31 11:29:43.050]
[0;32mI (1628) camera_httpd: Starting web server on port: '80'[0m[2023-03-31 11:29:43.057]
[0;32mI (1628) camera_httpd: Starting stream server on port: '81'[0m[2023-03-31 11:29:43.064]

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by WangYuxin-esp** [comment]
Sorry, the esp32-camera only provides a control interface for lighting up the sensor. Because the debugging of camera sensors relies heavily on the configuration of sensors, it is difficult for us to ensure that all sensors work well without the support of sensor FAE. During the project evaluation phase, I suggest that you use the OV2640 sensor on the official development board. After the project evaluation, please submit your requirements to our business personnel. We will provide suggestions for camera selection based on your needs and provide you with camera adaptation services.
