### ISSUE TITLE
什么时候会支持ESP-IDF 5.0  (AEGHB-184)

### ISSUE THREAD

**Issue by hyzgit** [espressif/esp-iot-solution#264]
When will ESP-IDF 5.0 be supported?

**Comment by leeebo** [comment]
@hyzgit 各个 example 是独立的，大部分已经同时支持 v4.4 和 v5.0 两个版本。你是指哪个 example ？

**Comment by hyzgit** [comment]
> @hyzgit 各个 example 是独立的，大部分已经同时支持 v4.4 和 v5.0 两个版本。你是指哪个 example ？

你好，这个例程，esp-iot-solution/examples/usb/host/usb_cdc_4g_module，接合宙的4G模块，比如air780E或者air724UG。
