### ISSUE TITLE
ble_ota can not work (AEGHB-265)

### ISSUE THREAD

**Issue by songzhishuo** [espressif/esp-iot-solution#279]
Version IDF 4.4.4

I don't know how to add this code to my project，run “idf.py create-project-from-example "espressif/ble_ota^0.1.8:ble_ota"” The error message is as follows:
-------------------------------------------

Executing action: all (aliases: build)
Running cmake in directory e:\work\outside_proj\esp32\example\blink\managed_components\espressif__cmake_utilities\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 e:\work\outside_proj\esp32\example\blink\managed_components\espressif__cmake_utilities"...
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Program Files/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Program Files/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:1 (idf_component_register):
  Unknown CMake command "idf_component_register".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.23)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

**Comment by wujiangang** [comment]
From the log:
```
Running cmake in directory e:\work\outside_proj\esp32\example\blink\managed_components\espressif__cmake_utilities\build
```

It seems that you entered folder `e:\work\outside_proj\esp32\example\blink\managed_components\espressif__cmake_utilities`, and do idf.py build.

please build this demo by following commands:
```
idf.py create-project-from-example "espressif/ble_ota^0.1.8:ble_ota"
cd ble_ota
idf.py build
```
