### ISSUE TITLE
uvc streaming start fail! error code -99 (AEGHB-348)

### ISSUE THREAD

**Issue by MaretArt** [espressif/esp-iot-solution#289]
i tried to connect usb camera to ESP32S3 using usb stream, but that failed! here is my terminal output!

â†�[0;33m--- idf_monitor on \\.\COM7 115200 ---â†�[0m
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
triï¿½ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0xa (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3810,len:0x17bc
load:0x403c9700,len:0xd7c
load:0x403cc700,len:0x300c
entry 0x403c992c
I (24) boot: ESP-IDF v5.0.2-dirty 2nd stage bootloader
I (25) boot: compile time 04:20:48
I (25) boot: chip revision: v0.1
I (27) qio_mode: Enabling default flash chip QIO
I (32) boot.esp32s3: Boot SPI Speed : 80MHz
I (37) boot.esp32s3: SPI Mode       : QIO
I (42) boot.esp32s3: SPI Flash Size : 2MB
I (47) boot: Enabling RNG early entropy source...
I (52) boot: Partition Table:
I (56) boot: ## Label            Usage          Type ST Offset   Length
I (63) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (70) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (78) boot:  2 factory          factory app      00 00 00010000 00100000
I (85) boot: End of partition table
I (90) esp_image: segment 0: paddr=00010020 vaddr=3c030020 size=10400h ( 66560) map
I (108) esp_image: segment 1: paddr=00020428 vaddr=3fc94400 size=02ad0h ( 10960) load
I (110) esp_image: segment 2: paddr=00022f00 vaddr=40374000 size=0d118h ( 53528) load
I (125) esp_image: segment 3: paddr=00030020 vaddr=42000020 size=2f270h (193136) map
I (155) esp_image: segment 4: paddr=0005f298 vaddr=40381118 size=032b4h ( 12980) load
I (164) boot: Loaded app from partition at offset 0x10000
I (164) boot: Disabling RNG early entropy source...
I (176) esp_psram: Found 2MB PSRAM device
I (176) esp_psram: Speed: 40MHz
I (176) cpu_start: Pro cpu up.
I (177) cpu_start: Starting app cpu, entry point is 0x40375520
0x40375520: call_start_cpu0 at C:/Espressif_v2.10.0/Espressif/frameworks/esp-idf-v5.0.2/components/esp_system/port/cpu_start.c:347

I (0) cpu_start: App cpu up.
I (602) esp_psram: SPI SRAM memory test OK
I (611) cpu_start: Pro cpu start user code
I (612) cpu_start: cpu freq: 160000000 Hz
I (612) cpu_start: Application information:
I (615) cpu_start: Project name:     app-template
I (620) cpu_start: App version:      1
I (624) cpu_start: Compile time:     Aug 14 2023 04:22:13
I (630) cpu_start: ELF file SHA256:  cfd229200ac8eeb8...
Warning: checksum mismatch between flashed and built applications. Checksum of built application is f1c30b67f201dd2b567cb40826482edb46cf3bf7c01a4b858da069abe62b11b4
I (636) cpu_start: ESP-IDF:          v5.0.2-dirty
I (642) cpu_start: Min chip rev:     v0.0
I (646) cpu_start: Max chip rev:     v0.99 
I (651) cpu_start: Chip rev:         v0.1
I (656) heap_init: Initializing. RAM available for dynamic allocation:
I (663) heap_init: At 3FC99910 len 0004FE00 (319 KiB): DRAM
I (669) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
I (676) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (682) heap_init: At 600FE010 len 00001FF0 (7 KiB): RTCRAM
I (689) esp_psram: Adding pool of 2048K of PSRAM memory to heap allocator
I (697) spi_flash: detected chip: gd
I (700) spi_flash: flash io: qio
W (704) spi_flash: Detected size(16384k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (718) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (738) esp_psram: Reserving pool of 32K of internal memory for DMA/internal allocations
Waiting for device
Device found
*** Device descriptor ***
bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0xef
bDeviceSubClass 0x2
bDeviceProtocol 0x1
bMaxPacketSize0 64
idVendor 0x1908
idProduct 0x2311
bcdDevice 1.00
iManufacturer 1
iProduct 2
iSerialNumber 0
bNumConfigurations 1
*** Configuration descriptor ***
bLength 9
bDescriptorType 2
wTotalLength 235
bNumInterfaces 2
bConfigurationValue 1
iConfiguration 0
bmAttributes 0x80
bMaxPower 256mA
*** Interface Association Descriptor ***
bLength 8
bDescriptorType 11
bFirstInterface 0
bInterfaceCount 2
bFunctionClass 0xe
bFunctionSubClass 0x3
bFunctionProtocol 0x0
iFunction 2
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 0
        bAlternateSetting 0
        bNumEndpoints 1
        bInterfaceClass 0xe
        bInterfaceSubClass 0x1
        bInterfaceProtocol 0x0
        iInterface 2
        *** Class-specific VC Interface Descriptor ***
        bLength 0xd
        bDescriptorType 0x24
        bDescriptorSubType 1
        bcdUVC 100
        wTotalLength 51
        dwClockFrequency 48000000
        bFunctionProtocol 1
        bInCollection 1
        baInterfaceNr 18
        *** Input Terminal Descriptor (Camera) ***
        bLength 0x12
        bDescriptorType 0x24
        bDescriptorSubType 2
        bTerminalID 1
        wTerminalType 201
        bAssocTerminal 0
        iTerminal 0
        wObjectiveFocalLengthMin 0
        wObjectiveFocalLengthMax 0
        wOcularFocalLength 0
        bControlSize 3
        bmControls 0x0
        *** Processing Unit Descriptor ***
        bLength 0xb
        bDescriptorType 0x24
        bDescriptorSubType 5
        bUnitID 2
        bSourceID 1
        wMaxMultiplier 0
        bControlSize 2
        bmControls 0x53f
        iProcessing 0
        bmVideoStandards 0x9
        *** Output Terminal Descriptor ***
        bLength 0x9
        bDescriptorType 0x24
        bDescriptorSubType 3
        bTerminalID 3
        wTerminalType 101
        bAssocTerminal 0
        bSourceID 2
        iTerminal 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x81   EP 1 IN
                bmAttributes 0x3        INT
                wMaxPacketSize 10
                bInterval 5
                *** Class-specific Interrupt Endpoint Descriptor ***
                bLength 0x5
                bDescriptorType 0x25
                bDescriptorSubType 3
                wMaxTransferSize 10
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 1
        bAlternateSetting 0
        bNumEndpoints 0
        bInterfaceClass 0xe
        bInterfaceSubClass 0x2
        bInterfaceProtocol 0x0
        iInterface 0
        *** Class-specific VC Interface Descriptor ***
        bLength 0xe
        bDescriptorType 0x24
        bDescriptorSubType 1
        bcdUVC 7301
        wTotalLength 33280
        dwClockFrequency 16909056
        bFunctionProtocol 1
        bInCollection 1
        baInterfaceNr 0
        *** Selector Unit Descriptor ***
        bLength 0x1b
        bDescriptorType 0x24
        bDescriptorSubType 4
        bUnitID 1
        bNrInPins 2
        baSourceID1 89
        baSourceID2 85
        iSelector 89
        *** Processing Unit Descriptor ***
        bLength 0x1e
        bDescriptorType 0x24
        bDescriptorSubType 5
        bUnitID 1
        bSourceID 0
        wMaxMultiplier 320
        bControlSize 240
        bmControls 0x0
        iProcessing 0
        bmVideoStandards 0x4b
        *** Processing Unit Descriptor ***
        bLength 0x1e
        bDescriptorType 0x24
        bDescriptorSubType 5
        bUnitID 2
        bSourceID 0
        wMaxMultiplier 160
        bControlSize 120
        bmControls 0x0
        iProcessing 80
        bmVideoStandards 0x46
        *** Output Terminal Descriptor ***
        bLength 0xe
        bDescriptorType 0x24
        bDescriptorSubType 3
        bTerminalID 0
        wTerminalType 4002
        bAssocTerminal 1
        bSourceID 240
        iTerminal 0
        *** VS Color Format Descriptor ***
        bLength 0x6
        bDescriptorType 0x24
        bDescriptorSubType 0xd
        bColorPrimaries 0x0
        bTransferCharacteristics 0
        bMatrixCoefficients 0x0
        *** Interface descriptor ***
        bLength 9
        bDescriptorType 4
        bInterfaceNumber 1
        bAlternateSetting 1
        bNumEndpoints 1
        bInterfaceClass 0xe
        bInterfaceSubClass 0x2
        bInterfaceProtocol 0x0
        iInterface 0
                *** Endpoint descriptor ***
                bLength 7
                bDescriptorType 5
                bEndpointAddress 0x82   EP 2 IN
                bmAttributes 0x5        ISOC
                wMaxPacketSize 768
                bInterval 1
*** String Descriptors ***
iProduct: USB2.0 PC CAMERA
iManufacturer: Generic
DEVICE CONFIGURATION (1908:2311/â•�â•š      â•�S) ---
Status: idle
VideoControl:
        bcdUVC: 0x0100
VideoStreaming(1):
        bEndpointAddress: 130
        Formats:
        UncompressedFormat(1)
                  bits per pixel: 16
                  GUID: 5955593200001000800000aa00389b71 (YUY2)
                  default frame: 1
                  aspect ratio: 0x0
                  interlace flags: 00
                  copy protect: 00
                        FrameDescriptor(1)
                          capabilities: 00
                          size: 320x240
                          bit rate: 4915200-4915200
                          max frame size: 153600
                          default interval: 1/4
                          interval[0]: 1/4
                        FrameDescriptor(2)
                          capabilities: 00
                          size: 160x120
                          bit rate: 4608000-4608000
                          max frame size: 38400
                          default interval: 1/15
                          interval[0]: 1/15
                        StillFrameDescriptor
                          bEndPointAddress: 00
                          wWidth(1) = 320
                          wHeight(1) = 240
                          wWidth(2) = 160
                          wHeight(2) = 120
END DEVICE CONFIGURATION
I (1588) USB CAMERA LCD DISPLAY 2: format_desc -> fourccFormat = (YUY2)
I (1598) USB CAMERA LCD DISPLAY 2: format_desc -> bFormatIndex = 1
I (1598) USB CAMERA LCD DISPLAY 2: frame_desc -> bFrameIndex = 1
I (1608) USB CAMERA LCD DISPLAY 2: frame_desc -> wWidth = 320
I (1618) USB CAMERA LCD DISPLAY 2: frame_desc -> wHeight = 240
I (1618) USB CAMERA LCD DISPLAY 2: format_desc -> bDescriptorSubtype = 4
I (1628) USB CAMERA LCD DISPLAY 2: frame_desc -> dwDefaultFrameInterval = 2500000
I (1638) USB CAMERA LCD DISPLAY 2: format_desc -> bDescriptorSubtype == UVC_VS_FORMAT_UNCOMPRESSED
W (1648) USB CAMERA LCD DISPLAY 2: Frame size 160x120, frame rate = 15
W (1648) USB CAMERA LCD DISPLAY 2: Frame format = YUYV
I (1658) USB CAMERA LCD DISPLAY 2: format = 3, width = 160, height = 120, fps = 15
bmHint: 0000
bFormatIndex: 1
bFrameIndex: 1
dwFrameInterval: 666666
wKeyFrameRate: 0
wPFrameRate: 0
wCompQuality: 0
wCompWindowSize: 0
wDelay: 0
dwMaxVideoFrameSize: 153600
dwMaxPayloadTransferSize: 512
bInterfaceNumber: 1
I (1688) USB CAMERA LCD DISPLAY 2: uvc_start_streaming = -99
E (1698) USB CAMERA LCD DISPLAY 2: uvc_streaming_start fail!
E (1698) USB CAMERA LCD DISPLAY 2: Change other camera and restart!

**Comment by leeebo** [comment]
@MaretArt Seems your camera can not support the MJPEG format. please refer https://github.com/espressif/esp-iot-solution/issues/285
