### ISSUE TITLE
Old version of esp-idf tagged in esp-iot-soloution/submodule/esp-idf

### ISSUE THREAD

**Issue by Kilill** [espressif/esp-iot-solution#29]
the esp-idf submodule should be updated to latest esp-idf release.
Currently it seems to be somewhere after V3.1

**Comment by InfiniteYuan1** [comment]
Thanks. We will update esp-idf  to lastest release as soon as possible.

**Comment by csobrinho** [comment]
Should it target 4.0 now? Thanks!

**Comment by InfiniteYuan1** [comment]
IDF submodule currently it is V3.2.

**Comment by leeebo** [comment]
Hi @csobrinho @Kilill , you can use [esp-iot-solution/tree/release/v1.1](https://github.com/espressif/esp-iot-solution/tree/release/v1.1) branch for your idf 4.0 projects.
