### ISSUE TITLE
编译aws_iot_demo报缺少certs/aws-root-ca.pem 这个文件，其他两个文件我已经从aws iot控制台下载了。

### ISSUE THREAD

**Issue by snailwft** [espressif/esp-iot-solution#3]
你好，
编译aws_iot_demo报缺少certs/aws-root-ca.pem 这个文件，其他两个文件我已经从aws iot控制台下载了。请问我怎么获取到aws-root-ca.pem？

**Comment by costaud** [comment]
Our engineer will reply soon.

**Comment by InfiniteYuan1** [comment]
您好！很高心能帮助到您。您可以参考在[AWS IoT Developer Guide](https://docs.aws.amazon.com/zh_cn/iot/latest/developerguide/create-device-certificate.html)''创建并激活设备证书''一节，将AWS IoT 的根 CA 下载到您的电脑上。

**Comment by snailwft** [comment]
您好，这个问题解决了，非常感谢！
