### ISSUE TITLE
请问为什么esp32 C6不支持EDR协议？ (AEGHB-470)

### ISSUE THREAD

**Issue by jankens** [espressif/esp-iot-solution#314]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

计划使用ESP32 C6，但是发现classic bt里的功能不能用，请问为什么不支持EDR？是软件没有实现吗？有没有可能在后续版本中增加对EDR的支持？

**Comment by zztiger123** [comment]
Hi [jankens](https://github.com/jankens)

目前 ESP 系列芯片中，只有 ESP32 支持经典蓝牙，其他芯片如 ESP32-C6 在硬件上就不支持经典蓝牙，所以后续软件版本也无法为其新增经典蓝牙功能。

因此，如您需要经典蓝牙，我们推荐您选择 ESP32。对应 datasheet 参见 https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_cn.pdf

**Comment by zztiger123** [comment]
经典蓝牙和BLE的基带都不同，硬件上也会有一些其他的不同。

**Comment by jankens** [comment]
请问esp32 c3是否支持经典蓝牙 EDR协议？
