### ISSUE TITLE
ESP32S3  edit Gateway IP (AEGHB-480)

### ISSUE THREAD

**Issue by VarnitNhrsl** [espressif/esp-iot-solution#316]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

How to change hotspot main gateway IP? currently it is 192.168.4.1, but I want 192.168.43.1. 
using ESP32s3 wroom 1.

**Comment by leeebo** [comment]
@VarnitNhrsl Hi, please refer the ESP-IDF example: https://github.com/espressif/esp-idf/blob/master/examples/protocols/static_ip/main/static_ip_example_main.c#L76
