### ISSUE TITLE
How can i use I2C with LittlevGL

### ISSUE THREAD

**Issue by colesnicov** [espressif/esp-iot-solution#34]
## Environment

- Development Kit:     ESP32-DevKitC
- Kit version: DevKitC/v3
- Module or chip used:  ESP32-WROOM-32
- IDF version :  3.1.3
- Build System:         Make
- Compiler version: 1.22.0-80-g6c4433a
- Operating System:     Linux
- Power Supply:         USB

## Problem Description

How can i use simultaneously `I2C` and `LittlevGL` or **`spi_lcd`**?

`I2C's` pins `21` and `22` are use for SPI as `MOSI` and `SCK`

**Comment by InfiniteYuan1** [comment]
The I2C's pins of ESP32 supports mapping to any IO with output capability.

```
    int i2c_master_port = I2C_MASTER_NUM;
    i2c_config_t conf;
    conf.mode = I2C_MODE_MASTER;
    conf.sda_io_num = I2C_MASTER_SDA_IO; // You want to have mapped IO
    conf.sda_pullup_en = GPIO_PULLUP_ENABLE;
    conf.scl_io_num = I2C_MASTER_SCL_IO; // You want to have mapped IO
    conf.scl_pullup_en = GPIO_PULLUP_ENABLE;
    conf.master.clk_speed = I2C_MASTER_FREQ_HZ;
    i2c_param_config(i2c_master_port, &conf);
```

You can refer to [I2C example](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/i2c).
