### ISSUE TITLE
esp-tinyuf2: hal/usb_phy_hal.h and hal/usb_phy_ll.h are renamed in esp-idf (AEGHB-615)

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/esp-iot-solution#349]
https://github.com/espressif/esp-iot-solution/blob/78ab2bc277f1b8909970a82a0156a35a493dabf2/components/usb/esp_tinyuf2/esp_tinyuf2.c#L18-L19

the header has been renamed by https://github.com/espressif/esp-idf/commit/1da17fce18e4fe55f50a0d65448fd49c0d4cddec

**Comment by leeebo** [comment]
@wuyuanyi135 Thanks for your report, will fix it
