### ISSUE TITLE
如何集成到Eclipse中去？ (AEGHB-637)

### ISSUE THREAD

**Issue by anmnmnly** [espressif/esp-iot-solution#354]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

一直使用Eclipse开发基于ESP-IDF的软件，现在需要用到IoT Solution，但官方的文档却使用命令行来安装。请问在Eclipse环境下应该如何安装？

**Comment by leeebo** [comment]
esp-iot-solution 中的每一个示例都是独立的，你可以直接克隆该仓库，打开你想要编译的[示例](https://github.com/espressif/esp-iot-solution/tree/master/examples)，进行编译，和 IDF 示例编译过程一致

如果想使用 esp-iot-solution 提供的组件，你可以直接复制对应组件到你的 project，或使用包管理器

详情请参考：https://github.com/espressif/esp-iot-solution?tab=readme-ov-file#quick-reference
