### ISSUE TITLE
关于pwm舵机控制的一些问题 (AEGHB-644)

### ISSUE THREAD

**Issue by welkinchan** [espressif/esp-iot-solution#356]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

1.请问怎样才能实现SG90舵机（180度舵机）的PWM调速？这里边又包括两个问题，一个是在舵机正常转速的基础上，有没办法实现增加速度。另外一个是，是否有舵机驱动库可以实现舵机速度的降低，比如乘以一个调速系数？
2. 我看了下，使用ledc的pwm进行驱动舵机的时候，ledc里边有一个函数，ledc_set_fade_with_time，从描述来看，它可以实现在限定时间来实现pwm占空比的变化。但是实际测试下来，在180度舵机上使用的话，会有很多异常，舵机转速不均匀，180度舵机进行了360度运动，未实现限定时间运动等等。

**Comment by lijunru-hub** [comment]
180度舵机的转速和当前角度以及期望角度的差有关系，差值越大转速越快。
理论上舵机的最大转速是不可以再调的，这和工作电压有关系，你可以将舵机的工作电压在可承受范围内加大。
如果想要舵机转速可调，可以将舵机的运动拆分成更小的步进值，如 1° / 2°
通过修改设置每个步进值之间的时间来达到调速的效果。
1. 增大速度：调大步进值，减小每个步进之间的间隔时间
2. 减小速度：调小步进值，增大每个步进之间的间隔时间
