### ISSUE TITLE
where the head file (AEGHB-683)

### ISSUE THREAD

**Issue by Dee-trigger** [espressif/esp-iot-solution#369]
### Answers checklist.

- [ ] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

<img width="647" alt="PixPin_2024-06-10_01-37-11" src="https://github.com/espressif/esp-iot-solution/assets/172206931/1d227924-b8a3-4059-91d7-77f08ffd63f6">
may be i am  fool but i reall can`t find it for me a jackaroo

**Comment by leeebo** [comment]
@Dee-trigger VSCode Editor Can not find headers, not means can not be found by Toolchain, if the ESP-IDF environment is exported correctly, it should be built without error

If you want Editor also find the files, please install ESP-IDF VSCode plugin, then follow the guide to add "ESP-IDF: Add vscode Configuration folder"
