### ISSUE TITLE
How to enable communication between PC and espS3 with USB dongle burned？ (AEGHB-720)

### ISSUE THREAD

**Issue by yunfusheng33** [espressif/esp-iot-solution#379]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2.2

### Espressif SoC revision.

esp32s3

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32-s3-DevkitC-1

### Power Supply used.

USB

### What is the expected behavior?

I burned usb_dongle to s3 and monitored the printed content through the serial port

### What is the actual behavior?

![Uploading 1720000817463.png…]()
 how should I send commands to s3 through a PC?

### Steps to reproduce.

none

**Comment by lijunru-hub** [comment]
link https://github.com/espressif/esp-iot-solution/issues/377
