### ISSUE TITLE
ADC based button and low power (AEGHB-800)

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-iot-solution#401]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The document only mentions GPIO based button support opportimization for lower power. How about ADC based button?

**Comment by lijunru-hub** [comment]
Unfortunately, the ADC peripheral cannot wake up the CPU. You can try increasing the polling interval to reduce power consumption.

**Comment by mike-2020** [comment]
got it, thanks.
