### ISSUE TITLE
led_indicator module can not control the index led, during ws2812 light strip (AEGHB-845)

### ISSUE THREAD

**Issue by Connor-WangK** [espressif/esp-iot-solution#414]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

ESP-IDF v5.3.1-240-g2dea1035d9

### Espressif SoC revision.

ESP32-C3 (QFN32) (revision v0.4)

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom board

### Steps to reproduce.

during light strip index control, the <set_brightness> step does not set index.
I change something in led_indicator.c hereinafter, 
after do this, things run well.

```
led_indicator.c line<464>

            // p_led_indicator->hal_indicator_set_brightness(p_led_indicator->hardware_data, led_indicator_get_gamma_value(brightness_value));
            p_led_indicator->hal_indicator_set_brightness(p_led_indicator->hardware_data, INSERT_INDEX(p_blink_step_value.i, brightness_value));

            ESP_LOGI(TAG, "bright: %"PRIx32, INSERT_INDEX(p_blink_step_value.i, brightness_value));
```

**Comment by lijunru-hub** [comment]
Thank you very much for raising this issue. We will fix it in the next version.
 
Best regards.
