### ISSUE TITLE
usb 摄像头无法加载成功 (AEGHB-884)

### ISSUE THREAD

**Issue by zhang1990xue** [espressif/esp-iot-solution#431]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3

### Espressif SoC revision.

esp32S3

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32S3

### Power Supply used.

External 5V

### What is the expected behavior?

上电后一直告警无法check short usb描述符

### What is the actual behavior?

E (5607) USB_STREAM: /IDF/esp-iot-solution/examples/usb/host/usb_camera_mic_spk/usb_camera_mic_spk/managed_components/espressif__usb_stream/usb_stream.c:3001 (_uvc_uac_device_enum):Enum abort
E (5608) USB_STREAM: ENUM Stage CHECK_SHORT_DEV_DESC, Failed
I (5608) USB_STREAM: Recover Stream Task
I (5629) USB_STREAM: Action: ACTION_PIPE_DFLT_DISABLE
I (5629) USB_STREAM: Resetting default pipe
I (5629) USB_STREAM: Action: ACTION_PIPE_DFLT_DISABLE, Done!
I (5630) USB_STREAM: Action: ACTION_PORT_RECOVER
I (5630) USB_STREAM: Action: ACTION_DEVICE_DISCONN
I (5630) USB_STREAM: Waiting USB Connection
I (5641) USB_STREAM: USB task xQueueReceive 1
I (5891) USB_STREAM: line 151 HCD_PORT_EVENT_CONNECTION
I (5891) USB_STREAM: Action: ACTION_DEVICE_CONNECT
I (5941) USB_STREAM: Resetting Port
I (6001) USB_STREAM: Setting Port FIFO, 1
I (6001) USB_STREAM: Action: ACTION_DEVICE_CONNECT, Done!
I (6001) USB_STREAM: Action: ACTION_DEVICE_ENUM Stage NONE (0)
I (6002) USB_STREAM: USB Speed: full-speed
I (6002) USB_STREAM: pipe(0x3fccbc5c) init succeed
I (6002) USB_STREAM: ENUM Stage START, Succeed
I (6002) USB_STREAM: Action: ACTION_DEVICE_ENUM, Done (0)
I (6004) USB_STREAM: Action: ACTION_DEVICE_ENUM Stage GET_SHORT_DEV_DESC (2)
I (6004) USB_STREAM: ENUM Stage GET_SHORT_DEV_DESC, Succeed
I (6004) USB_STREAM: Action: ACTION_DEVICE_ENUM, Waiting URB Done
I (6005) USB_STREAM: Action: ACTION_DEVICE_ENUM, Done (2)
I (10988) USB_STREAM: USB task xQueueReceive 1
W (10988) USB_STREAM: line 155 HCD_PORT_EVENT_DISCONNECTION
E (10988) USB_STREAM: /IDF/esp-iot-solution/examples/usb/host/usb_camera_mic_spk/usb_camera_mic_spk/managed_components/espressif__usb_stream/usb_stream.c:3001 (_uvc_uac_device_enum):Enum abort
E (10989) USB_STREAM: ENUM Stage CHECK_SHORT_DEV_DESC, Failed
I (10990) USB_STREAM: Recover Stream Task

### Steps to reproduce.

上电就这样。例子是
D:\Espressif\frameworks\esp-idf-v5.3.1\esp-iot-solution\examples\usb\host\usb_camera_mic_spk
...

### Debug Logs.

```plain
E (5607) USB_STREAM: /IDF/esp-iot-solution/examples/usb/host/usb_camera_mic_spk/usb_camera_mic_spk/managed_components/espressif__usb_stream/usb_stream.c:3001 (_uvc_uac_device_enum):Enum abort
E (5608) USB_STREAM: ENUM Stage CHECK_SHORT_DEV_DESC, Failed
I (5608) USB_STREAM: Recover Stream Task
I (5629) USB_STREAM: Action: ACTION_PIPE_DFLT_DISABLE
I (5629) USB_STREAM: Resetting default pipe
I (5629) USB_STREAM: Action: ACTION_PIPE_DFLT_DISABLE, Done!
I (5630) USB_STREAM: Action: ACTION_PORT_RECOVER
I (5630) USB_STREAM: Action: ACTION_DEVICE_DISCONN
I (5630) USB_STREAM: Waiting USB Connection
I (5641) USB_STREAM: USB task xQueueReceive 1
I (5891) USB_STREAM: line 151 HCD_PORT_EVENT_CONNECTION
I (5891) USB_STREAM: Action: ACTION_DEVICE_CONNECT
I (5941) USB_STREAM: Resetting Port
I (6001) USB_STREAM: Setting Port FIFO, 1
I (6001) USB_STREAM: Action: ACTION_DEVICE_CONNECT, Done!
I (6001) USB_STREAM: Action: ACTION_DEVICE_ENUM Stage NONE (0)
I (6002) USB_STREAM: USB Speed: full-speed
I (6002) USB_STREAM: pipe(0x3fccbc5c) init succeed
I (6002) USB_STREAM: ENUM Stage START, Succeed
I (6002) USB_STREAM: Action: ACTION_DEVICE_ENUM, Done (0)
I (6004) USB_STREAM: Action: ACTION_DEVICE_ENUM Stage GET_SHORT_DEV_DESC (2)
I (6004) USB_STREAM: ENUM Stage GET_SHORT_DEV_DESC, Succeed
I (6004) USB_STREAM: Action: ACTION_DEVICE_ENUM, Waiting URB Done
I (6005) USB_STREAM: Action: ACTION_DEVICE_ENUM, Done (2)
I (10988) USB_STREAM: USB task xQueueReceive 1
W (10988) USB_STREAM: line 155 HCD_PORT_EVENT_DISCONNECTION
E (10988) USB_STREAM: /IDF/esp-iot-solution/examples/usb/host/usb_camera_mic_spk/usb_camera_mic_spk/managed_components/espressif__usb_stream/usb_stream.c:3001 (_uvc_uac_device_enum):Enum abort
E (10989) USB_STREAM: ENUM Stage CHECK_SHORT_DEV_DESC, Failed
I (10990) USB_STREAM: Recover Stream Task
```

### More Information.

no

**Comment by leeebo** [comment]
@zhang1990xue ESP32-S3 拿不到该摄像头的 fullspeed 模式下的描述符，说明该设备不支持 fullspeed 下运行。需要更换摄像头，或者使用支持 USB Highspeed 的 ESP 芯片（例如 ESP32-P4）
