### ISSUE TITLE
Camera Initialization Issue on ESP32-S3 Custom PCB (AEGHB-895)

### ISSUE THREAD

**Issue by hardikofficial963** [espressif/esp-iot-solution#436]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

We are currently developing a custom PCB based on the ESP32-S3 that integrates the following components:
    - OV5640 Camera
    - ES8311 Codec IC (for microphone and speaker functionality)
    - Servo Port
    - I2C Port
    - SD Card Port

While all other components are functioning as expected, we are facing a recurring issue with the camera.

Issue Description:
The PCB works fine initially after assembly, but after some time, the camera fails to initialize, showing errors such as:

    "Camera initialization error"
    "Camera SCCB failed"

Steps Taken:

1. Testing with Custom PCB:
The camera works immediately after assembly but stops functioning after some time.
Testing with ESP32-S3 Development Board:

2. We connected the OV5640 camera using an FFC breakout board and the same pins used in the custom PCB. The same initialization errors occur.

Attachments for Reference:
    - PCB Design Schematic  (1-4, 2-4)
    - PCB Layout   (3-4)
    - List of Pins Used  (4-4)

Could you please help us identify and resolve the issue? Any insights or suggestions would be greatly appreciated.

Looking forward to your guidance.
![Camera_pcb_1-4](https://github.com/user-attachments/assets/e640a637-ab62-4532-bdb0-09a5b7df6b07)
![Camera_pcb_2-4](https://github.com/user-attachments/assets/3ba5b3fb-61c8-4e81-b3fc-cad3d86e52cf)
![Camera_pins_4-4](https://github.com/user-attachments/assets/15812e55-c354-47ff-881f-5883320f2c5e)
![Camera_Schematic_3-4](https://github.com/user-attachments/assets/711f740e-f689-4244-b869-c11c3c1b8a16)

**Comment by leeebo** [comment]
Closing due to duplicate issue https://github.com/espressif/esp-idf/issues/14947
