### ISSUE TITLE
USB Camera 设备描述符解析错误 (AEGHB-898)

### ISSUE THREAD

**Issue by NuclearRee** [espressif/esp-iot-solution#439]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3.1

### Espressif SoC revision.

ESP32S3 UTG USB

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

usb_stream.c

### Steps to reproduce.

使用ESP32S3 OTG USB开发板进行开发，使用官方示例项目usb_camera_mic_spk进行摄像头推流时。接入摄像头后发现usb设备描述符解析与windows的 usbtreeview.exe解析结果不一致，导致识别不到usbCamera的Video Streaming MJPEG Format Type Descriptor，无法进行摄像头推流。不一致数据如下图所示
![企业微信截图_20241201222504](https://github.com/user-attachments/assets/02230e77-3e8d-4cc7-ab8e-82b436c7b80d)

**Comment by lijunru-hub** [comment]
应该是你这个摄像头不支持在 USB 1.1 Full Speed 下工作，可以用接上 USB 隔离器后再抓一下描述符。

It seems that your camera does not support working in USB 1.1 Full Speed mode. You can try connecting it through a USB isolator and then capture the descriptors again.

**Comment by NuclearRee** [comment]
> 应该是你这个摄像头不支持在 USB 1.1 Full Speed 下工作，可以用接上 USB 隔离器后再抓一下描述符。
> 
> It seems that your camera does not support working in USB 1.1 Full Speed mode. You can try connecting it through a USB isolator and then capture the descriptors again.

尝试了一下接了一个usbhub后无法识别到设备了
![image](https://github.com/user-attachments/assets/62b4e7ab-732b-4939-9eb1-df44324d0df0)
下面是用usbtreeview解析的文件
[usb.md](https://github.com/user-attachments/files/17971999/usb.md)

**Comment by lijunru-hub** [comment]
usb stream 不支持 USB HUB， USB 隔离器不是 USB HUB，是强制设备运行在 FullSpeed 的设备。
看 log 你这个摄像头在 PC 下是走的 HighSpeed 运行的。你得确定这个设备支不支持 USB FullSpeed。
有些摄像头在 HighSpeed 下可以正常工作，但是可能 FullSpeed 下就没有那么多格式选择，甚至不支持
![image](https://github.com/user-attachments/assets/7c3dec2a-f229-4952-9843-b6a380616884)

**Comment by NuclearRee** [comment]
> usb stream 不支持 USB HUB， USB 隔离器不是 USB HUB，是强制设备运行在 FullSpeed 的设备。 看 log 你这个摄像头在 PC 下是走的 HighSpeed 运行的。你得确定这个设备支不支持 USB FullSpeed。 有些摄像头在 HighSpeed 下可以正常工作，但是可能 FullSpeed 下就没有那么多格式选择，甚至不支持 ![image](https://private-user-images.githubusercontent.com/68437239/391400575-7c3dec2a-f229-4952-9843-b6a380616884.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTAyOTUsIm5iZiI6MTczMzEwOTk5NSwicGF0aCI6Ii82ODQzNzIzOS8zOTE0MDA1NzUtN2MzZGVjMmEtZjIyOS00OTUyLTk4NDMtYjZhMzgwNjE2ODg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAzMjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMTU0Njk4NTM1NDAxMDI3NGIyM2E0NTc2ODExNWM1M2E5OTBjOTVhOTdkMDVkZDU0YTYzMGNkYzM1MmI3M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cjJgiq9Q8VW9oxNL7ej51Hpby3kebB7lLWJREnhNrbU)

我又查看了一下设备描述符，有全速模式下的描述符，发现就是我们选取的摄像头不支持全速模式下运行。
可以通过修改驱动层来适配HighSpeed的usb设备？硬件层面会有问题吗

**Comment by NuclearRee** [comment]
> usb stream 不支持 USB HUB， USB 隔离器不是 USB HUB，是强制设备运行在 FullSpeed 的设备。 看 log 你这个摄像头在 PC 下是走的 HighSpeed 运行的。你得确定这个设备支不支持 USB FullSpeed。 有些摄像头在 HighSpeed 下可以正常工作，但是可能 FullSpeed 下就没有那么多格式选择，甚至不支持 ![image](https://private-user-images.githubusercontent.com/68437239/391400575-7c3dec2a-f229-4952-9843-b6a380616884.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTAyOTUsIm5iZiI6MTczMzEwOTk5NSwicGF0aCI6Ii82ODQzNzIzOS8zOTE0MDA1NzUtN2MzZGVjMmEtZjIyOS00OTUyLTk4NDMtYjZhMzgwNjE2ODg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAzMjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMTU0Njk4NTM1NDAxMDI3NGIyM2E0NTc2ODExNWM1M2E5OTBjOTVhOTdkMDVkZDU0YTYzMGNkYzM1MmI3M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cjJgiq9Q8VW9oxNL7ej51Hpby3kebB7lLWJREnhNrbU)

我又查看了一下设备的那就是我们选取的摄像头不支持全速模式下运行。

可以通过修改驱动层来适配HighSpeed的usb设备？

**Comment by lijunru-hub** [comment]
硬件限定的，除非你换 ESP32-P4
