### ISSUE TITLE
Update for lvgl 6.0?

### ISSUE THREAD

**Issue by Aiouan** [espressif/esp-iot-solution#44]
Hi,
Is there an ETA to update the IoT commit to be compatible with lvgl V6.0?
It has basically become unusable.

**Comment by InfiniteYuan1** [comment]
Hey, the lvgl version will not be updated in the near future.

However, I can help you with the transplant,
First of all, you should know the port process through the official website of lvgl.
After that, modify it based on the v5.3 porting.

Thanks.

**Comment by Aiouan** [comment]
Thanks, I have moved my projects to use the kisvegabor framework which already supports V6
