### ISSUE TITLE
espressif/esp_lcd_st7701 using very old version of LVGL (AEGHB-900)

### ISSUE THREAD

**Issue by seulater** [espressif/esp-iot-solution#441]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

In the examples folder for esp_lcd_st7701, it is using a very outdated lvgl as the example. 
Are there plans to get this updated to using the latest lvgl v9.2.2 ?

**Comment by Horion0415** [comment]
You can refer to the example: https://github.com/espressif/esp-iot-solution/blob/master/examples/display/lcd/rgb_lcd_8bit/main/example_rgb_lcd_8bit.c. This project supports the latest version of LVGL, but the LCD driver part needs to be modified to support the ST7701.
