### ISSUE TITLE
camera build issue  ERROR: Because project depends on espressif/camera (*) which doesn't (AEGHB-921)

### ISSUE THREAD

**Issue by achao1104** [espressif/esp-iot-solution#449]
I just copied esp-iot-solution/examples/camera/basic to a new folder, 
and  run idf.py set-target esp32s3, it get following error:

CMake Error at /opt/esp/esp-idf/tools/cmake/build.cmake:552 (message):
  ERROR: The "override_path" field in the manifest file
  "/opt/esp/common_components/camera/idf_component.yml" does not point to a
  directory.  You can safely remove this field from the manifest if this
  project is an example copied from a component repository.  The dependency

If I removed "override_path", and like below:
dependencies:
  idf: ">=4.4.1"
  camera:
    version: "*"
  esp32-camera:
    version: ">=2.0.3"

run idf.py set-target esp32s3, it get following error:

..HINT: Please check manifest file of the following component(s): main
CMake Error at /opt/esp/esp-idf/tools/cmake/build.cmake:552 (message):
  WARNING: Component "espressif/camera" not found

  ERROR: Because project depends on espressif/camera (*) which doesn't match
  any versions, version solving failed.

**Comment by leeebo** [comment]
@achao1104 that's because the `common_components/camera` not released to esp-registry

Please build the example under the esp-iot-solution folder, or copy the `camera` to your `examples/camera/basic/components`
