### ISSUE TITLE
README example is missing `bme280_default_init(bme280);` (AEGHB-925)

### ISSUE THREAD

**Issue by gknops** [espressif/esp-iot-solution#451]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The README.md example code, Step 2 should have this additional line at the end:

`bme280_default_init(bme280);`

Without it the sample code will run but not return any results.

**Comment by YanKE01** [comment]
Hi, @gknops . Thank you very much! The issue will be fixed as soon as possible.
