### ISSUE TITLE
esp-iot-solution library for "esp32 azure Iot" board

### ISSUE THREAD

**Issue by ChristosPalisidis** [espressif/esp-iot-solution#46]
Hello,
I have a problem using the aforementioned library. I get the message "no headers files (.h) found in C:\............\Arduino\libraries\esp-iot-solution".
Can someone provide information about the usage of this library?
Thank you in advance!

**Comment by fivdi** [comment]
Information about usage of the library is provided in [README.md](https://github.com/espressif/esp-iot-solution/blob/master/README.md). To the best of my knowledge the library isn't designed for usage with the Arduino IDE.
