### ISSUE TITLE
Custom fonts for ssd1306 component

### ISSUE THREAD

**Issue by colesnicov** [espressif/esp-iot-solution#47]
Hi all. Please, I managed to break up the ssd1306 component under esp8266 (esp-12F). But now I have another question, I found no mention of how to create and add my own fonts? Thank you for the hint :)

**Comment by colesnicov** [comment]
Esperessif, I mean really.  we need to be able to create our own fonts.  Including extended fonts !!  Thank you for your response.  Would it be some kind of guidance or tool ...

**Comment by wibsea** [comment]
Look at this file, everything is simple there:
 ~/esp/esp-iot-solution/components/i2c_devices/others/ssd1306/ssd1306_fonts.c
