### ISSUE TITLE
Can't find DataScope application

### ISSUE THREAD

**Issue by webstdave** [espressif/esp-iot-solution#6]
Touch sensor readme refers to "DataScope tool can be downloaded from Espressif's official website." but I cannot find it. Could someone provide a link, please?  Thank you!

**Comment by NareshDealer** [comment]
i m looking for same.. anyone has a downloaded copy.?

**Comment by Cojocari** [comment]
Have you managed to find that tool ? And if not. how did you calibrated sense kit? Thank you.

**Comment by InfiniteYuan1** [comment]
[ESP-Tuning Tool](http://download.espressif.com/application_release/ESP-Tuning_Tool.zip)
[esp_tuning_tool_user_guide_en.md](https://github.com/espressif/esp-iot-solution/blob/master/documents/touch_pad_solution/esp_tuning_tool_user_guide_en.md)
[ESP-Tuning Tool Code](https://github.com/espressif/esp-iot-solution/tree/master/components/features/touchpad)
