### ISSUE TITLE
A4988 driver issue with ledc_set_freq

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-iot-solution#65]
Hi,
i am trying to get working A4988 and i can make it working with 2 issues.
1) bug in ledc.c i already opened issue in esp-idf repository,
2) there is problem with `ledc_set_freq` this exact line:
https://github.com/espressif/esp-iot-solution/blob/master/components/motor/stepper/a4988/a4988.cpp#L255

This line return ESP_OK, but motor is no longer working. When i comment out this line everything seems to works fine.

esp-idf v3.3
EDIT `ledc_set_freq` seems to be fixed in master
EDIT2 if its possible to backport fix to v3.3 and create PR to AWSFreeRTOS it would be awesome

Thanks for code and help.

**Comment by chegewara** [comment]
Hi,
is there possible to backport fix for this to v3.3 or at least to have patch i can use wiith AFR?

@projectgus any help please

**Comment by projectgus** [comment]
Hi @chegewara,

This looks like an issue in the IDF driver not  the IoT solution, so I'll reply to you on that issue: https://github.com/espressif/esp-idf/issues/4476

**Comment by chegewara** [comment]
Yes, i realized it after finding core issue, but didnt want to open another issue.
Thanks

**Comment by projectgus** [comment]
@chegewara The fix in this driver is to choose LEDC_REF_TICK if you plan to set low frequency PWM speeds (approx <1MHz?), and LEDC_APB_CLK otherwise. But it should produce an error instead of silently turning off the PWM output.
