### ISSUE TITLE
Unable to clone ugfx submodule

### ISSUE THREAD

**Issue by InfiniteYuan** [espressif/esp-iot-solution#68]
You may encounter this error when updating submodule of esp-iot-solution.

```
Cloning into '/esp-iot-solution/components/hmi/ugfx_gui/ugfx'...
fatal: unable to access 'https://git.ugfx.io/ugfx/ugfx.git/': SSL certificate problem: certificate has expired
fatal: clone of 'https://git.ugfx.io/ugfx/ugfx.git' into submodule path '/esp-iot-solution/components/hmi/ugfx_gui/ugfx' failed
Failed to clone 'components/hmi/ugfx_gui/ugfx'. Retry scheduled
```

Solution:

```
env GIT_SSL_NO_VERIFY=true git submodule update --init --recursive
```

**Comment by zztiger123** [comment]
Hi, InfiniteYuan1 

Thank you for your support, I would appreciate it!

best regards,

**Comment by wibsea** [comment]
Brave decision! :) Maybe wait a bit?

**Comment by carson2017** [comment]
Great! Thanks a lot, I have been puzzled by this problem for a long time

**Comment by Alexlizx** [comment]
I now get a slightly different error:
`Cloning into 'C:/Users/Documents/ESP-IDF/esp-iot-solution/components/hmi/ugfx_gui/ugfx'...
fatal: unable to access 'https://git.ugfx.io/ugfx/ugfx.git/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

I'm working on a Windows environment so "env GIT_SSL_NO_VERIFY=true" does not work. I tried other ways to disable ssl verification but always come back to the same error.

**Comment by Xiehanxin** [comment]
@InfiniteYuan  If this issue is now resolved, please close it. Thank you.

**Comment by MrityunjaiKumar** [comment]
Its a SSL issue, the git server for this dependency got ssl certificate issue.

In [.gitmodules](https://github.com/espressif/esp-iot-solution/blob/master/.gitmodules), I changed  

https://git.ugfx.io/ugfx/ugfx.git
to
http://git.ugfx.io/ugfx/ugfx.git 

there after use following command.

`git submodule sync`

It worked for me!
