### ISSUE TITLE
Read register from MCU8080 port

### ISSUE THREAD

**Issue by andid-sntu** [espressif/esp-iot-solution#70]
Now I need to use the register to read port 8080 device. I tried to modify the 
"void i2s_lcd_write_cmd(i2s_lcd_handle_t i2s_lcd_handle, uint8_t CMD) "function, 
but failed. 
Could you please add the function to read port 8080 in the following file:
 esp-iot-solution/components/i2s_devices/lcd_common/i2s_lcd_com.c

**Comment by InfiniteYuan1** [comment]
Please wait a few days.
Thanks.
