### ISSUE TITLE
uGFX + SSD1306 won't compile

### ISSUE THREAD

**Issue by malachib** [espressif/esp-iot-solution#74]
## Environment

- Module or chip used:  ESP32
- IDF version (run ``git describe --tags`` to find it): v3.3.1
- Build System:         Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 1.22.0-80-g6c4433a
- Operating System:     macOS
- Power Supply:         USB

## Problem Description

Completely empty uGFX project fails compilation at uGFX component level, as described a year ago here: https://esp32.com/viewtopic.php?f=22&t=8437

### Expected Behavior

To bring up a boilerplate uGFX SSD1306 project with no special capabilities

### Actual Behavior

Compilation error:

```
/Users/Malachi/Projects/ext/esp-iot-solution/components/hmi/gdrivers/gdisp/framebuffer/gdisp_lld_framebuffer.c: In function 'gdisp_lld_control':
/Users/Malachi/Projects/ext/esp-iot-solution/components/hmi/gdrivers/gdisp/framebuffer/gdisp_lld_framebuffer.c:123:13: error: implicit declaration of function 'board_lcd_set_orientation' [-Werror=implicit-function-declaration]
             board_lcd_set_orientation(0);
             ^
```

### Steps to repropduce

git clone and try compiling the project here:
https://bitbucket.org/malachib/playground.esp/src/master/src/PGESP-2.iot/

**Comment by leeebo** [comment]
We are sorry the repository stopped supporting the uGFX, we suggest you use LVGL instead

The ESP-IDF has integrated LVGL from v5.0, you can use the component https://components.espressif.com/components/espressif/esp_lvgl_port instead, and you can find more examples in https://github.com/espressif/esp-idf/tree/master/examples/peripherals/lcd and https://github.com/espressif/esp-bsp/tree/master/esp32_s3_lcd_ev_board
