### ISSUE TITLE
Upgrade to esp-idf v4.0

### ISSUE THREAD

**Issue by Kilill** [espressif/esp-iot-solution#75]
Is there an ETA for upgrade to esp-idf v4.0 ?

**Comment by salocinx** [comment]
What is the latest ESP-IDF version supported by this example?

**Comment by leeebo** [comment]
Hi , [esp-iot-solution/tree/release/v1.1](https://github.com/espressif/esp-iot-solution/tree/release/v1.1) based on idf v4.0.1, you can use it now. And we are working on porting esp-iot-solution to the latese idf version to support new Socs.
