### ISSUE TITLE
怎么在睡眠模式下，发送固定的广播？

### ISSUE THREAD

**Issue by xpdrycry** [espressif/esp-iot-solution#80]
你好，1.想知道如何在睡眠模式下，进行广播的发送？2.还有如果在睡眠模式下，这种功耗大概是多少？

**Comment by Xiehanxin** [comment]
在睡眠模式下如果要进行广播，会先对芯片进行唤醒然后发送广播，结束后回归睡眠低功耗状态。所以整体的功耗和你广播的时间与频率有关。
If your mcu is working  in the sleep mode, it awakes when  need broadcast (both wifi and bluetooth). and return to sleep after broadcast. The power consumption depends on the  broadcast frequency you set.
