### ISSUE TITLE
请问有计划适配 ESP32S2 的计划吗 

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-iot-solution#86]
请问有计划适配 ESP32S2 的计划吗

**Comment by leeebo** [comment]
Different chips will be unified through same API in unreleased ESP-IDF v4.2.
ESP-IDF v4.2 will be supported in esp-iot-solution after ESP-IDF v4.2 released.

**Comment by Xiehanxin** [comment]
If your issue is now resolved, can you please close the issue. Thank you.

**Comment by xuhongv** [comment]
- How long can support ESP32-S2?

**Comment by leeebo** [comment]
@xuhongv Which component or example do you need for ESP32-S2 ?  we will firstly update it.

**Comment by xuhongv** [comment]
Driver of using LittlevGL embedded GUI library.

Thanks. @leeebo

**Comment by leeebo** [comment]
@xuhongv ESP32-S2 supported now. Welcome to test and contribute.
