### ISSUE TITLE
Power meter on ESP8266

### ISSUE THREAD

**Issue by colesnicov** [espressif/esp-iot-solution#87]
## Environment

- Development Kit:      WEMOS D1 mini
- IDF version: v3.2-502-gda3362ec
- Build System:         Make
- Compiler version: xtensa-lx106-elf-gcc (crosstool-NG crosstool-ng-1.22.0-100-ge567ec7) 5.2.0
- Operating System:     Linux
- Power Supply:         USB

## Problem Description

Hello. I try to compile the Power_meter component but I get this error:
`power_meter.c:20:25: fatal error: driver/pcnt.h: No such file or directory`

**Comment by alic-maker** [comment]
What command did you use to compile this component?

I recommend that you use  [release/v1.1](https://github.com/espressif/esp-iot-solution/tree/release/v1.1)

**Comment by colesnicov** [comment]
I just type 
```
make
```

**Comment by alic-maker** [comment]
You can try the following command to compile
```shell
cd tools/unit-test-app
make TEST_COMPONENTS="power_meter" -j8  && make flash monitor
```
