### ISSUE TITLE
where to download the esp32 secure flasher tool?

### ISSUE THREAD

**Issue by philar** [espressif/esp-iot-solution#9]
Question as the title show , can show me the download link of the esp32 secure flasher tool, mention in  document  "https://github.com/espressif/esp-iot-solution/blob/master/documents/security_solution/download_tool_en.md#download-tool-gui-instruction"

**Comment by costaud** [comment]
You can download the latest version [here](download.espressif.com/release/flash_download_tools_v3.6.5.zip).
