### ISSUE TITLE
Button create bug

### ISSUE THREAD

**Issue by Lisa999** [espressif/esp-iot-solution#93]
> use esp timer !!!
I (976) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 
use esp timer !!!
E (986) gpio: gpio_install_isr_service(439): GPIO isr service already installed
I (996) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 

Function 'iot_button_create' line 316 in file button.c: gpio_install_isr_service(0);
Shouldn't call this function for the 2nd (or more) button create!

**Comment by leeebo** [comment]
A new button framework is added, you can try https://github.com/espressif/esp-iot-solution/tree/master/components/button

**Comment by Lisa999** [comment]
New button framework is working great!
