### ISSUE TITLE
CMake Error at CMakeLists.txt:20 (register_component)

### ISSUE THREAD

**Issue by exrector** [espressif/esp-iot-solution#94]
`Running cmake in directory /Users/exrector/esp-iot-solution/components/motor/servo/servo_motor/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 --warn-uninitialized -DIDF_TARGET=esp32 -DCCACHE_ENABLE=0 /Users/exrector/esp-iot-solution/components/motor/servo/servo_motor"...
Warn about uninitialized values.
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (register_component):
  Unknown CMake command "register_component".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.18)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/Users/exrector/esp-iot-solution/components/motor/servo/servo_motor/build/CMakeFiles/CMakeOutput.log".
See also "/Users/exrector/esp-iot-solution/components/motor/servo/servo_motor/build/CMakeFiles/CMakeError.log".
cmake failed with exit code 1`

**Comment by TDA-2030** [comment]
Which branch are you using？

**Comment by exrector** [comment]
> Какую ветку вы используете？

1.1

**Comment by TDA-2030** [comment]
@exrector Which version of esp-idf are you using？The esp-iot-solution v1.1 should be compiled using esp-idf v4.0.1

**Comment by exrector** [comment]
I used idf4.1. Is it not working with esp-iot-solution v1.1 ?

> @exrector Какую версию esp-idf вы используете？ esp-iot-solution v1.1 должен быть скомпилирован с использованием esp-idf v4.0.1.
> Как вы использовали компонент servo_motor? Как происходит процесс компиляции и какие команды используются？

@TDA-2030 
I used idf4.1. Is it not working with esp-iot-solution v1.1 ?

**Comment by exrector** [comment]
@TDA-2030 
simple /Users/exrector/esp-iot-solution/examples/hmi/lvgl_example

MacExrector:lvgl_example Exrector$ idf.py set-target esp32
Adding "set-target"'s dependency "fullclean" to list of commands with default set of options.
Executing action: fullclean
Directory '/Users/exrector/esp-iot-solution/examples/hmi/lvgl_example/build' doesn't seem to be a CMake build directory. Refusing to automatically delete files in this directory. Delete the directory manually to 'clean' it.
MacExrector:lvgl_example Exrector$ idf.py fullclean
Executing action: fullclean
Build directory '/Users/exrector/esp-iot-solution/examples/hmi/lvgl_example/build' not found. Nothing to clean.
Done
MacExrector:lvgl_example Exrector$ idf.py set-target esp32
Executing action: set-target
Set Target to: esp32, new sdkconfig created. Existing sdkconfig renamed to sdkconfig.old.
Running cmake in directory /Users/exrector/esp-iot-solution/examples/hmi/lvgl_example/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 --warn-uninitialized -DIDF_TARGET=esp32 -DCCACHE_ENABLE=0 /Users/exrector/esp-iot-solution/examples/hmi/lvgl_example"...
Warn about uninitialized values.
CMake Error at CMakeLists.txt:15 (include):
  include could not find load file:

    /esp/esp-idf/CMakeLists.txt


-- Found Git: /usr/local/bin/git (found version "2.28.0") 
-- Unexpected file in components directory: /Users/exrector/esp/esp-idf/components/.DS_Store
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /Users/exrector/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/exrector/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/exrector/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project version: 4f5689f-dirty
-- Building ESP-IDF components for target esp32
Loading defaults file /Users/exrector/esp-iot-solution/examples/hmi/lvgl_example/sdkconfig.defaults...
/Users/exrector/esp-iot-solution/examples/hmi/lvgl_example/sdkconfig.defaults:102 CONFIG_TIMER_TASK_STACK_DEPTH was replaced with CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:39 line was updated to CONFIG_BIT_MODE_8BIT=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:45 line was updated to CONFIG_UGFX_GUI_ENABLE=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:46 line was updated to CONFIG_SELECT_NONE=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:51 line was updated to CONFIG_LVGL_USE_CUSTOM_DRIVER=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:55 line was updated to CONFIG_LVGL_LCD_DRIVER_API_MODE=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:57 line was updated to CONFIG_LVGL_DRIVER_DOUBLE_BUFFER_ENABLE=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:58 line was updated to CONFIG_LVGL_DISP_ROTATE_0=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:60 line was updated to CONFIG_LVGL_DISP_ROTATE_180=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:61 line was updated to CONFIG_LVGL_DISP_ROTATE_270=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:67 line was updated to CONFIG_LVGL_DRIVER_TOUCH_FT5X06=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:74 line was updated to CONFIG_LVGL_DRIVER_ILI9341=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:75 line was updated to CONFIG_LVGL_DRIVER_SSD1306=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:77 line was updated to CONFIG_LVGL_DRIVER_NT35510=n
/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/confgen_tmpHbSor8:83 line was updated to CONFIG_LVGL_LCD_VSPI=n
-- Found PythonInterp: /Users/exrector/.espressif/python_env/idf4.1_py2.7_env/bin/python (found version "2.7.18") 
-- Found Perl: /usr/bin/perl (found version "5.28.2") 
-- Adding linker script /Users/exrector/esp-iot-solution/examples/hmi/lvgl_example/build/esp-idf/esp32/esp32_out.ld
-- Adding linker script /Users/exrector/esp/esp-idf/components/esp32/ld/esp32.project.ld.in
-- Adding linker script /Users/exrector/esp/esp-idf/components/esp32/ld/esp32.peripherals.ld
-- Adding linker script /Users/exrector/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-time.ld
-- Adding linker script /Users/exrector/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.ld
-- Adding linker script /Users/exrector/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
-- Adding linker script /Users/exrector/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-data.ld
-- Adding linker script /Users/exrector/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.syscalls.ld
-- Adding linker script /Users/exrector/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
-- Components: app_trace app_update asio bootloader bootloader_support bt cbor coap console cxx driver efuse esp-tls esp32 esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_http_client esp_http_server esp_https_ota esp_https_server esp_local_ctrl esp_netif esp_ringbuf esp_rom esp_serial_slave_link esp_websocket_client esp_wifi espcoredump esptool_py expat fatfs freemodbus freertos heap idf_test jsmn json libsodium log lwip main mbedtls mdns mqtt newlib nghttp nvs_flash openssl partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spiffs tcp_transport tcpip_adapter ulp unity vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
-- Component paths: /Users/exrector/esp/esp-idf/components/app_trace /Users/exrector/esp/esp-idf/components/app_update /Users/exrector/esp/esp-idf/components/asio /Users/exrector/esp/esp-idf/components/bootloader /Users/exrector/esp/esp-idf/components/bootloader_support /Users/exrector/esp/esp-idf/components/bt /Users/exrector/esp/esp-idf/components/cbor /Users/exrector/esp/esp-idf/components/coap /Users/exrector/esp/esp-idf/components/console /Users/exrector/esp/esp-idf/components/cxx /Users/exrector/esp/esp-idf/components/driver /Users/exrector/esp/esp-idf/components/efuse /Users/exrector/esp/esp-idf/components/esp-tls /Users/exrector/esp/esp-idf/components/esp32 /Users/exrector/esp/esp-idf/components/esp_adc_cal /Users/exrector/esp/esp-idf/components/esp_common /Users/exrector/esp/esp-idf/components/esp_eth /Users/exrector/esp/esp-idf/components/esp_event /Users/exrector/esp/esp-idf/components/esp_gdbstub /Users/exrector/esp/esp-idf/components/esp_http_client /Users/exrector/esp/esp-idf/components/esp_http_server /Users/exrector/esp/esp-idf/components/esp_https_ota /Users/exrector/esp/esp-idf/components/esp_https_server /Users/exrector/esp/esp-idf/components/esp_local_ctrl /Users/exrector/esp/esp-idf/components/esp_netif /Users/exrector/esp/esp-idf/components/esp_ringbuf /Users/exrector/esp/esp-idf/components/esp_rom /Users/exrector/esp/esp-idf/components/esp_serial_slave_link /Users/exrector/esp/esp-idf/components/esp_websocket_client /Users/exrector/esp/esp-idf/components/esp_wifi /Users/exrector/esp/esp-idf/components/espcoredump /Users/exrector/esp/esp-idf/components/esptool_py /Users/exrector/esp/esp-idf/components/expat /Users/exrector/esp/esp-idf/components/fatfs /Users/exrector/esp/esp-idf/components/freemodbus /Users/exrector/esp/esp-idf/components/freertos /Users/exrector/esp/esp-idf/components/heap /Users/exrector/esp/esp-idf/components/idf_test /Users/exrector/esp/esp-idf/components/jsmn /Users/exrector/esp/esp-idf/components/json /Users/exrector/esp/esp-idf/components/libsodium /Users/exrector/esp/esp-idf/components/log /Users/exrector/esp/esp-idf/components/lwip /Users/exrector/esp-iot-solution/examples/hmi/lvgl_example/main /Users/exrector/esp/esp-idf/components/mbedtls /Users/exrector/esp/esp-idf/components/mdns /Users/exrector/esp/esp-idf/components/mqtt /Users/exrector/esp/esp-idf/components/newlib /Users/exrector/esp/esp-idf/components/nghttp /Users/exrector/esp/esp-idf/components/nvs_flash /Users/exrector/esp/esp-idf/components/openssl /Users/exrector/esp/esp-idf/components/partition_table /Users/exrector/esp/esp-idf/components/perfmon /Users/exrector/esp/esp-idf/components/protobuf-c /Users/exrector/esp/esp-idf/components/protocomm /Users/exrector/esp/esp-idf/components/pthread /Users/exrector/esp/esp-idf/components/sdmmc /Users/exrector/esp/esp-idf/components/soc /Users/exrector/esp/esp-idf/components/spi_flash /Users/exrector/esp/esp-idf/components/spiffs /Users/exrector/esp/esp-idf/components/tcp_transport /Users/exrector/esp/esp-idf/components/tcpip_adapter /Users/exrector/esp/esp-idf/components/ulp /Users/exrector/esp/esp-idf/components/unity /Users/exrector/esp/esp-idf/components/vfs /Users/exrector/esp/esp-idf/components/wear_levelling /Users/exrector/esp/esp-idf/components/wifi_provisioning /Users/exrector/esp/esp-idf/components/wpa_supplicant /Users/exrector/esp/esp-idf/components/xtensa
-- Configuring incomplete, errors occurred!
See also "/Users/exrector/esp-iot-solution/examples/hmi/lvgl_example/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1
MacExrector:lvgl_example Exrector$
