### ISSUE TITLE
mistakes in motor a4988

### ISSUE THREAD

**Issue by exrector** [espressif/esp-iot-solution#95]
^~~~~~~
../main/a4988.cpp:64:5: error: 'SemaphoreHandle_t' does not name a type; did you mean 'xSemaphoreHandle'?
     SemaphoreHandle_t sem;
     ^~~~~~~~~~~~~~~~~
     xSemaphoreHandle
../main/a4988.cpp:65:5: error: 'SemaphoreHandle_t' does not name a type; did you mean 'xSemaphoreHandle'?
     SemaphoreHandle_t mux;
     ^~~~~~~~~~~~~~~~~
     xSemaphoreHandle
../main/a4988.cpp: In function 'void stepper_pcnt_intr_handler(void*)':
../main/a4988.cpp:88:40: error: 'struct stepper_dev_t' has no member named 'sem'
             xSemaphoreGiveFromISR(dev->sem, &HPTaskAwoken);
                                        ^~~
../main/a4988.cpp:88:13: error: 'xSemaphoreGiveFromISR' was not declared in this scope
             xSemaphoreGiveFromISR(dev->sem, &HPTaskAwoken);
             ^~~~~~~~~~~~~~~~~~~~~
../main/a4988.cpp:88:13: note: suggested alternative: 'xQueueGiveFromISR'
             xSemaphoreGiveFromISR(dev->sem, &HPTaskAwoken);
             ^~~~~~~~~~~~~~~~~~~~~
             xQueueGiveFromISR
../main/a4988.cpp: In constructor 'CA4988Stepper::CA4988Stepper(int, int, int, ledc_mode_t, ledc_timer_t, ledc_channel_t, pcnt_unit_t, pcnt_channel_t)':
../main/a4988.cpp:142:15: error: 'struct stepper_dev_t' has no member named 'sem'
     pstepper->sem = xSemaphoreCreateBinary();
               ^~~
../main/a4988.cpp:142:21: error: 'xSemaphoreCreateBinary' was not declared in this scope
     pstepper->sem = xSemaphoreCreateBinary();
                     ^~~~~~~~~~~~~~~~~~~~~~
../main/a4988.cpp:142:21: note: suggested alternative: 'xSemaphoreHandle'
     pstepper->sem = xSemaphoreCreateBinary();
                     ^~~~~~~~~~~~~~~~~~~~~~
                     xSemaphoreHandle
../main/a4988.cpp:143:15: error: 'struct stepper_dev_t' has no member named 'mux'
     pstepper->mux = xSemaphoreCreateMutex();
               ^~~
../main/a4988.cpp:143:21: error: 'xSemaphoreCreateMutex' was not declared in this scope
     pstepper->mux = xSemaphoreCreateMutex();
                     ^~~~~~~~~~~~~~~~~~~~~
../main/a4988.cpp:143:21: note: suggested alternative: 'xQueueCreateMutex'
     pstepper->mux = xSemaphoreCreateMutex();
                     ^~~~~~~~~~~~~~~~~~~~~
                     xQueueCreateMutex
../main/a4988.cpp: In member function 'esp_err_t CA4988Stepper::stop(bool)':
../main/a4988.cpp:209:34: error: 'struct stepper_dev_t' has no member named 'sem'
         xSemaphoreGive(pstepper->sem);
                                  ^~~
../main/a4988.cpp:209:9: error: 'xSemaphoreGive' was not declared in this scope
         xSemaphoreGive(pstepper->sem);
         ^~~~~~~~~~~~~~
../main/a4988.cpp:209:9: note: suggested alternative: 'xSemaphoreHandle'
         xSemaphoreGive(pstepper->sem);
         ^~~~~~~~~~~~~~
         xSemaphoreHandle
../main/a4988.cpp: In member function 'esp_err_t CA4988Stepper::wait()':
../main/a4988.cpp:265:30: error: 'struct stepper_dev_t' has no member named 'mux'
     xSemaphoreTake(pstepper->mux, portMAX_DELAY);
                              ^~~
../main/a4988.cpp:265:5: error: 'xSemaphoreTake' was not declared in this scope
     xSemaphoreTake(pstepper->mux, portMAX_DELAY);
     ^~~~~~~~~~~~~~
../main/a4988.cpp:265:5: note: suggested alternative: 'xSemaphoreHandle'
     xSemaphoreTake(pstepper->mux, portMAX_DELAY);
     ^~~~~~~~~~~~~~
     xSemaphoreHandle
../main/a4988.cpp:267:34: error: 'struct stepper_dev_t' has no member named 'sem'
         xSemaphoreTake(pstepper->sem, portMAX_DELAY);
                                  ^~~
../main/a4988.cpp:269:30: error: 'struct stepper_dev_t' has no member named 'mux'
     xSemaphoreGive(pstepper->mux);
                              ^~~
../main/a4988.cpp:269:5: error: 'xSemaphoreGive' was not declared in this scope
     xSemaphoreGive(pstepper->mux);
     ^~~~~~~~~~~~~~
../main/a4988.cpp:269:5: note: suggested alternative: 'xSemaphoreHandle'
     xSemaphoreGive(pstepper->mux);
     ^~~~~~~~~~~~~~
     xSemaphoreHandle
../main/a4988.cpp: In member function 'esp_err_t CA4988Stepper::run(int, bool)':
../main/a4988.cpp:277:30: error: 'struct stepper_dev_t' has no member named 'mux'
     xSemaphoreTake(pstepper->mux, portMAX_DELAY);
                              ^~~
../main/a4988.cpp:277:5: error: 'xSemaphoreTake' was not declared in this scope
     xSemaphoreTake(pstepper->mux, portMAX_DELAY);
     ^~~~~~~~~~~~~~
../main/a4988.cpp:277:5: note: suggested alternative: 'xSemaphoreHandle'
     xSemaphoreTake(pstepper->mux, portMAX_DELAY);
     ^~~~~~~~~~~~~~
     xSemaphoreHandle
../main/a4988.cpp:278:30: error: 'struct stepper_dev_t' has no member named 'sem'
     xSemaphoreTake(pstepper->sem, 0);
                              ^~~
../main/a4988.cpp:304:30: error: 'struct stepper_dev_t' has no member named 'mux'
     xSemaphoreGive(pstepper->mux);
                              ^~~
../main/a4988.cpp:304:5: error: 'xSemaphoreGive' was not declared in this scope
     xSemaphoreGive(pstepper->mux);
     ^~~~~~~~~~~~~~
../main/a4988.cpp:304:5: note: suggested alternative: 'xSemaphoreHandle'
     xSemaphoreGive(pstepper->mux);
     ^~~~~~~~~~~~~~
     xSemaphoreHandle
../main/a4988.cpp: In member function 'esp_err_t CA4988Stepper::step(int, TickType_t, bool)':
../main/a4988.cpp:311:30: error: 'struct stepper_dev_t' has no member named 'mux'
     xSemaphoreTake(pstepper->mux, portMAX_DELAY);
                              ^~~
../main/a4988.cpp:311:5: error: 'xSemaphoreTake' was not declared in this scope
     xSemaphoreTake(pstepper->mux, portMAX_DELAY);
     ^~~~~~~~~~~~~~
../main/a4988.cpp:311:5: note: suggested alternative: 'xSemaphoreHandle'
     xSemaphoreTake(pstepper->mux, portMAX_DELAY);
     ^~~~~~~~~~~~~~
     xSemaphoreHandle
../main/a4988.cpp:329:30: error: 'struct stepper_dev_t' has no member named 'sem'
     xSemaphoreTake(pstepper->sem, 0);
                              ^~~
../main/a4988.cpp:348:47: error: 'struct stepper_dev_t' has no member named 'sem'
     BaseType_t res = xSemaphoreTake(pstepper->sem, ticks_to_wait);
                                               ^~~
../main/a4988.cpp:349:30: error: 'struct stepper_dev_t' has no member named 'mux'
     xSemaphoreGive(pstepper->mux);
                              ^~~
../main/a4988.cpp:349:5: error: 'xSemaphoreGive' was not declared in this scope
     xSemaphoreGive(pstepper->mux);
     ^~~~~~~~~~~~~~
../main/a4988.cpp:349:5: note: suggested alternative: 'xSemaphoreHandle'
     xSemaphoreGive(pstepper->mux);
     ^~~~~~~~~~~~~~
     xSemaphoreHandle
../main/a4988.cpp: In destructor 'CA4988Stepper::~CA4988Stepper()':
../main/a4988.cpp:361:32: error: 'struct stepper_dev_t' has no member named 'mux'
     vSemaphoreDelete(pstepper->mux);
                                ^~~
../main/a4988.cpp:361:5: error: 'vSemaphoreDelete' was not declared in this scope
     vSemaphoreDelete(pstepper->mux);
     ^~~~~~~~~~~~~~~~
../main/a4988.cpp:361:5: note: suggested alternative: 'xSemaphoreHandle'
     vSemaphoreDelete(pstepper->mux);
     ^~~~~~~~~~~~~~~~
     xSemaphoreHandle
../main/a4988.cpp:362:32: error: 'struct stepper_dev_t' has no member named 'sem'
     vSemaphoreDelete(pstepper->sem);
                                ^~~
[1117/1128] Building CXX object esp-id...df_asio.dir/asio/asio/src/asio.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by alic-maker** [comment]
It looks like is a compatibility issue，try to replace SemaphoreHandle_t with xSemaphoreHandle.
