### ISSUE TITLE
eth2wifi - arduino example

### ISSUE THREAD

**Issue by DavidAntonin** [espressif/esp-iot-solution#96]
Is it possible to get a working example in Arduino IDE?

**Comment by Raeymeister** [comment]
That would be great. Since it is unclear to me how to get a working esp32 w/ eth2wifi now. 
Many thanks!

**Comment by leeebo** [comment]
Hi @Raeymeister @DavidAntonin Please add the feature request to https://github.com/espressif/esp-iot-bridge, the solution will be maintained there
