### ISSUE TITLE
ugfx git repository is invalid

### ISSUE THREAD

**Issue by veryxs** [espressif/esp-iot-solution#97]
when i git clone esp-iot-solution，I get the following error

`Cloning into '/mnt/d/workspace/esp32/esp-iot-solution/components/hmi/ugfx_gui/ugfx'...
fatal: unable to access 'https://git.ugfx.io/ugfx/ugfx.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
fatal: clone of 'https://git.ugfx.io/ugfx/ugfx.git' into submodule path '/mnt/d/workspace/esp32/esp-iot-solution/components/hmi/ugfx_gui/ugfx' failed
Failed to clone 'components/hmi/ugfx_gui/ugfx' a second time, aborting`

I cannot download it completely，hope it can be fixed

**Comment by leeebo** [comment]
Thansks for your feedback, we will fix it very soon.

for temporary fix :
1. modify https->http here: https://github.com/leeebo/esp-iot-solut ... odules#L15
2. run `git submodule sync` to update the submodule's url
3. run `git submodule update --init --recursive` to pull the submodule
