### ISSUE TITLE
Missing i2c_master_stop(cmd)

### ISSUE THREAD

**Issue by MadsHHLund** [espressif/esp-iot-solution#98]
I think a few lines are missing in mcp23017.c

I have made the following changes which make write_byte and write work.

esp_err_t iot_mcp23017_write_byte(mcp23017_handle_t dev, uint8_t reg_addr,   uint8_t data)
{
    printf("write byte reg %i data %i tickrate %i\n",reg_addr,data,portTICK_RATE_MS);
    esp_err_t ret;
    mcp23017_dev_t* device = (mcp23017_dev_t*) dev;
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (device->dev_addr << 1) | WRITE_BIT,  ACK_CHECK_EN);
    i2c_master_write_byte(cmd, reg_addr, ACK_CHECK_EN);
    i2c_master_write_byte(cmd, data, ACK_CHECK_EN);

    i2c_master_stop(cmd);// tilføjet mads

    ret = iot_i2c_bus_cmd_begin(device->bus, cmd, 1000 / portTICK_RATE_MS);
    i2c_cmd_link_delete(cmd);
    return ret;
}

esp_err_t iot_mcp23017_write(mcp23017_handle_t dev, uint8_t reg_start_addr,   uint8_t reg_num, uint8_t *data_buf)
{
    uint32_t i = 0;
    i2c_cmd_handle_t cmd;
    esp_err_t ret = ESP_FAIL;
    mcp23017_dev_t* device = (mcp23017_dev_t*) dev;
    if (data_buf != NULL) {
        cmd = i2c_cmd_link_create();
            i2c_master_start(cmd);
            i2c_master_write_byte(cmd, (device->dev_addr << 1) | WRITE_BIT,               ACK_CHECK_EN);
            i2c_master_write_byte(cmd, reg_start_addr , ACK_CHECK_EN);// slettet + i

          for (i = 0; i < reg_num; i++) {   // flyttet et par linjer ned....
              i2c_master_write_byte(cmd, data_buf[i], ACK_CHECK_EN);
          }
        i2c_master_stop(cmd);// Tilføjet af  mads lund
        ret = iot_i2c_bus_cmd_begin(device->bus, cmd, 1000 / portTICK_RATE_MS);
        i2c_cmd_link_delete(cmd);
    }
    return ret;
}

**Comment by leeebo** [comment]
Hi, you can try the new [mcp23017](https://github.com/espressif/esp-iot-solution/tree/master/components/expander/io_expander/mcp23017) driver.
